---
title: "characterize_migration_strategies2"
author: "MNSnyder"
date: "12/19/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(cowplot)
library(data.table)
library(knitr)
library(chron)
library(lubridate)
library(dplyr)
library(plotly)
library(GGally)
library(doBy) # statistical summary function
```


###################################
Statistical Summary function

```{r statistical summary function}
## Summarizes data.
## Gives count, mean, standard deviation, standard error of the mean, and confidence 
## interval (default 95%).
##   data: a data frame.
##   measurevar: the name of a column that contains the variable to be summariezed
##   groupvars: a vector containing names of columns that contain grouping variables
##   na.rm: a boolean that indicates whether to ignore NA's
##   conf.interval: the percent range of the confidence interval (default is 95%)
summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE, conf.interval=.95) {
    library(doBy)

    # New version of length which can handle NA's: if na.rm==T, don't count them
    length2 <- function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else       length(x)
    }

    # Collapse the data
    formula <- as.formula(paste(measurevar, paste(groupvars, collapse=" + "), sep=" ~ "))
    datac <- summaryBy(formula, data=data, FUN=c(length2,mean,sd), na.rm=na.rm)

    # Rename columns
    names(datac)[ names(datac) == paste(measurevar, ".mean",    sep="") ] <- measurevar
    names(datac)[ names(datac) == paste(measurevar, ".sd",      sep="") ] <- "sd"
    names(datac)[ names(datac) == paste(measurevar, ".length2", sep="") ] <- "N"
    
    datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean
    
    # Confidence interval multiplier for standard error
    # Calculate t-statistic for confidence interval: 
    # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
    ciMult <- qt(conf.interval/2 + .5, datac$N-1)
    datac$ci <- datac$se * ciMult
    
    return(datac)
}
```

#################################
Import end condition data for 4 scenarios

```{r import end condition data, eval=TRUE}
# import in combined replicate DFs
A13<-read.table("D:/Results_4Populations/gr_Columbia2017B/combined/E13.csv", header=TRUE, sep=",")
B13<-read.table("D:/Results_4Populations/gr_Columbia2017B_NoCWR/combined/F13.csv", header=TRUE, sep=",")
C13<-read.table("D:/Results_4Populations/gr_Columbia2017BplusOne/combined/G13.csv", header=TRUE, sep=",")
D13<-read.table("D:/Results_4Populations/gr_Columbia2017BplusOne_NoCWR/combined/H13.csv", header=TRUE, sep=",")

# rename DF columns
names(A13)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")
names(B13)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")
names(C13)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")
names(D13)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")

```

#######################################
Import temperature data
```{r import temp table and format, eval=TRUE, include=FALSE}
# import table of water temperatures
water_temps<-read.table("D:/HexSim_Models/CWR_Columbia/Columbia [small]/Analysis/Data Lookup/Columbia2017B_TribsCurrent.csv", header = FALSE, sep = ",")

```

#####################
Format data
```{r format temperature data}
# first row is bonneville teemperature, drop all rows except first
bonn_temp<-water_temps[2,]
bonn_temp2<-t(bonn_temp) # transpose to long
colnames(bonn_temp2)<-"bonn_temp" # change column name
# add column for time step
timestep<-seq(from=1,to=dim(bonn_temp2)[1],by=1) # create sequence for number of hours of temp
#timestep<-seq(from=1, to=2928, by=1)
temp<-cbind.data.frame(bonn_temp2, timestep)
plot(bonn_temp2~timestep, data=temp, ylab="Bonneville Temperature", xlab=c("Model hour"))
```


```{r get maximum Bonneville temperature hour}
# figure out what hottest temperature is
max_temp<-max(temp$bonn_temp)
# leave only hours in DF with highest temperature
all_max_temps<-dplyr::filter(temp, bonn_temp2 == max_temp)
# choose latest model hour of max temp
row_no<-dim(all_max_temps)[1]
max_temp_hour<-all_max_temps$timestep[4]
```


Create function to calculate:
* Entry Timing
* Total_hours_cold_water
* time in system not in CWR = ReservoirH
* Initial weight

```{r function to calculate end condition metrics}

# function to calculate cumulative degree days above a certain degree

avail_energy_diff<-function(DF){
  DF$gamete<-(((7598 + (0.527 * DF$Initial_weight)) * DF$Initial_weight) * 0.068) / DF$Initial_weight
DF$initial_ED_avail<-DF$Initial_energy_density-DF$gamete
# create column of energy lost
# energy_all$energy_lost<-energy_all$X11 - energy_all$X13
DF$energy_lost_gamete<-(DF$initial_ED_avail - DF$Fitness_energy) 
DF$ED_per_used<-(DF$energy_lost_gamete/DF$initial_ED_avail) * 100
return(DF)
}

# entry timing as related to maximum water temperature function

entry_timing_f <- function(DF, temp_data){
  # figure out what hottest temperature is
  max_temp<-max(temp_data$bonn_temp)
  # leave only hours in DF with highest temperature
  all_max_temps<-dplyr::filter(temp_data, bonn_temp2 == max_temp)
  # choose latest model hour of max temp
  row_no<-dim(all_max_temps)[1]
  # select one max temperature hour
  max_temp_hour<-all_max_temps$timestep[row_no]
  # get entry time value
  DF$EntryTiming<-DF$Time_entry - max_temp_hour
  #DF$EntryPeriod<-ifelse(DF$Time_entry < 1000, "A", ifelse(DF$Time_entry > 1800), "C", "B")
  #as.factor(DF$EntryPeriod)
  return(DF)
}

# combine functions into one function

calculate_metrics <- function(DF, temp_data){
  # calculate entry timing
  A<-entry_timing_f(DF, temp_data)
  # select columns
  A_minus<-select(A, ID, EntryTiming)
  
  # calculate time in system outside CWR
  DF$ReservoirH <- DF$Time_in_system - DF$Total_hours_cold_water
  # rename total hours in CWR column
  DF<-rename(DF, cwrH = Total_hours_cold_water)
  # drop unnecessary columns
  B_minus<-select(DF, ID, ReservoirH, cwrH, Initial_weight)
  
  # calculate % energy density lost
  C<-avail_energy_diff(DF)
  # drop unnecessary columns
  C_minus<-select(C, ID, ED_per_used)
  
  # combine for final data
  out1<-merge(A_minus, B_minus, by.x="ID", by.y="ID")
  metrics_all<-merge(out1, C_minus, by.x="ID", by.y="ID")
  
  return(metrics_all)
}


```


```{r calculate metrics}

A_end <- calculate_metrics(A13, temp)
A_end$scenario <- "Current with CWRs"

B_end <- calculate_metrics(B13, temp)
B_end$scenario <- "Current without CWRs"

C_end <- calculate_metrics(C13, temp)
C_end$scenario <- "Future with CWRs"

D_end <- calculate_metrics(D13, temp)
D_end$scenario <- "Future without CWRs"

# combine all scenarios
abcd_end<-rbind.data.frame(A_end, B_end, C_end, D_end)
# convert scenario to factor
abcd_end$scenario <- as.factor(abcd_end$scenario)

# create winners
abcd_win<-filter(abcd_end, ED_per_used < 25)
```


```{r exploratory plots}

# entry timing vs. reservoir hours by scenario
ggplot(data=abcd_win, aes(x=EntryTiming, y=ReservoirH, colour=scenario, fill=scenario)) + 
  geom_point()+ theme_classic(base_size=10)+
  xlab("Entry Timing") + ylab("Reservoir (h)")+ 
  scale_color_manual(breaks=c("Current with CWRs", "Current without CWRs", "Future with CWRs", "Future without CWRs"), values=c("lightblue",  "red", "darkblue", "yellow"))

# speed by cluster
summary_speed<-summarySE(abcd_win, measurevar = "ReservoirH", groupvars = c("scenario"))

# The errorbars overlapped, so use position_dodge to move them horizontally
pd <- position_dodge(0.1) # move them .05 to the left and right


ggplot(summary_speed, aes(x=scenario, y=ReservoirH, colour=scenario, fill=scenario)) +
  geom_errorbar(aes(ymin=ReservoirH - ci, ymax=ReservoirH + ci), width = 0.1, position=pd) +
  geom_point(position=pd) + 
  xlab("Migration Strategy") + ylab("Reservoir (h)")+
 scale_color_manual(breaks=c("Current with CWRs", "Current without CWRs", "Future with CWRs", "Future without CWRs"), values=c("lightblue",  "red", "darkblue", "yellow"))+
  theme_classic(base_size=20) + 
  theme(legend.position = "none")


```


```{r}

abcd_win$EntryTiming_c<-ifelse(abcd_win$EntryTiming < -400, "A", ifelse(abcd_win$EntryTiming > -50, "C", "B"))

#aggregate(ReservoirH~EntryTiming_c + scenario, data=abcd_win, mean)


# speed by cluster
summary_speed<-summarySE(abcd_win, measurevar = "ReservoirH", groupvars = c("EntryTiming_c", "scenario"))

# The errorbars overlapped, so use position_dodge to move them horizontally
pd <- position_dodge(0.1) # move them .05 to the left and right


ggplot(summary_speed, aes(x=scenario, y=ReservoirH, colour=EntryTiming_c, fill=EntryTiming_c)) + geom_errorbar(aes(ymin=ReservoirH - ci, ymax=ReservoirH + ci), width = 0.1, position=pd) +
  geom_point(position=pd) + 
  xlab("Migration Strategy") + ylab("Reservoir (h)")+
 scale_color_manual(breaks=c("A","B","C"), values=c("lightblue",  "red", "darkblue"))+
  theme_classic(base_size=15) 

ggplot(abcd_win, aes(x=EntryTiming_c, y=ReservoirH, colour=scenario, fill=scenario)) + geom_boxplot()+
  xlab("Migration Strategy") + ylab("Reservoir (h)")+
  theme_classic(base_size=15) 

ggplot(summary_speed, aes(x=EntryTiming_c, y=ReservoirH, colour=scenario, fill=scenario)) + geom_errorbar(aes(ymin=ReservoirH - sd, ymax=ReservoirH + sd), width = 0.1, position=pd) +
  geom_point(position=pd) + 
  xlab("Migration Strategy") + ylab("Reservoir (h)")+
  theme_classic(base_size=15) 
```



```{r}
# entry timing vs. weight by scenario
ggplot(data=abcd_win, aes(x=EntryTiming, y=Initial_weight, colour=scenario, fill=scenario)) + 
  geom_point()+ theme_classic(base_size=10)+
  xlab("Entry Timing") + ylab("Initial weight (g)")+ 
  scale_color_manual(breaks=c("Current with CWRs", "Current without CWRs", "Future with CWRs", "Future without CWRs"), values=c("lightblue",  "red", "darkblue", "yellow"))

```



```{r try smoothing}
d<-ggplot(data=abcd_win, aes(x=EntryTiming, y=ReservoirH)) + 
  geom_point()+ theme_bw(base_size=15)+
  xlab("Entry Timing") + ylab("Reservoir (h)") 


d + stat_density_2d(aes(fill = stat(nlevel)), geom = "polygon") +
  facet_grid(.~ scenario ) + scale_fill_viridis_c() 


d<-ggplot(data=abcd_win, aes(x=EntryTiming, y=ReservoirH)) + 
  geom_point()+ theme_bw(base_size=10)+
  xlab("Entry Timing") + ylab("Reservoir (h)") 


d + stat_density_2d(aes(fill = stat(nlevel)), geom = "polygon") +
  facet_grid(scenario ~ .) + scale_fill_viridis_c() 
#+geom_hline(aes(yintercept =350, col="red" ))
```



