---
title: "Grande Ronde summer steelhead summarized fitness outcomes"
author: "MNSnyder"
date: "9/04/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

Grande Ronde summer steelhead Columbia River temperature time series from 2017. 
4 scenarios included:

* Columbia River 2017
* Columbia River 2017, no CWRs
* Columbia River 2017 plus 1
* Columbia River 2017 plus 1, no CWRs

Columbia 2017A assigns the John Day Pool temperature from the John Day forebay, which is the warmer part of the pool.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
library(ggplot2)
library(cowplot)
library(data.table)
library(knitr)
library(chron)
```


```{r import end condition}
# import in combined replicate DFs
A13<-read.table("D:/Results_4Populations/gr_Columbia2017B/combined/E13.csv", header=TRUE, sep=",")
B13<-read.table("D:/Results_4Populations/gr_Columbia2017B_NoCWR/combined/F13.csv", header=TRUE, sep=",")
C13<-read.table("D:/Results_4Populations/gr_Columbia2017BplusOne/combined/G13.csv", header=TRUE, sep=",")
D13<-read.table("D:/Results_4Populations/gr_Columbia2017BplusOne_NoCWR/combined/H13.csv", header=TRUE, sep=",")

# rename DF columns
names(A13)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")
names(B13)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")
names(C13)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")
names(D13)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")

```


```{r created energy used for all scenarios without gamete}
# function to calculate cumulative degree days above a certain degree
avail_energy_diff<-function(DF){
  DF$gamete<-(((7598 + (0.527 * DF$Initial_weight)) * DF$Initial_weight) * 0.068) / DF$Initial_weight
DF$initial_ED_avail<-DF$Initial_energy_density-DF$gamete
# create column of energy lost
# energy_all$energy_lost<-energy_all$X11 - energy_all$X13
DF$energy_lost_gamete<-(DF$initial_ED_avail - DF$Fitness_energy) 
DF$ED_per_used<-(DF$energy_lost_gamete/DF$initial_ED_avail) * 100
return(DF)
}

A13<-avail_energy_diff(A13)
B13<-avail_energy_diff(B13)
C13<-avail_energy_diff(C13)
D13<-avail_energy_diff(D13)

# add scenario identifying column
A13$scenario<-"A"
B13$scenario<-"B"
C13$scenario<-"C"
D13$scenario<-"D"

# combine DFs 
all_13<-rbind.data.frame(A13, B13, C13, D13)
```


```{r created energy used for all scenarios, eval=FALSE, include=FALSE}
# A13$energy_density_used<-A13$Initial_energy_density-A13$Fitness_energy_density
# A13$ED_per_used<-(A13$energy_density_used / A13$Initial_energy_density) * 100
# A13$scenario<-"A"
# 
# B13$energy_density_used<-B13$Initial_energy_density-B13$Fitness_energy_density
# B13$ED_per_used<-(B13$energy_density_used / B13$Initial_energy_density) * 100
# B13$scenario<-"B"
# 
# C13$energy_density_used<-C13$Initial_energy_density-C13$Fitness_energy_density
# C13$ED_per_used<-(C13$energy_density_used / C13$Initial_energy_density) * 100
# C13$scenario<-"C"
# 
# D13$energy_density_used<-D13$Initial_energy_density-D13$Fitness_energy_density
# D13$ED_per_used<-(D13$energy_density_used / D13$Initial_energy_density) * 100
# D13$scenario<-"D"
# 
# E13$energy_density_used<-E13$Initial_energy_density-E13$Fitness_energy_density
# E13$ED_per_used<-(E13$energy_density_used / E13$Initial_energy_density) * 100
# E13$scenario<-"E"
# 
# F13$energy_density_used<-F13$Initial_energy_density-F13$Fitness_energy_density
# F13$ED_per_used<-(F13$energy_density_used / F13$Initial_energy_density) * 100
# F13$scenario<-"F"
# 
# G13$energy_density_used<-G13$Initial_energy_density-G13$Fitness_energy_density
# G13$ED_per_used<-(G13$energy_density_used / G13$Initial_energy_density) * 100
# G13$scenario<-"G"
# 
# all_13<-rbind.data.frame(A13, B13, C13, D13, E13, F13, G13)
```

```{r plot formatting}
width1 = 4.5
height1 = 3.5
text1 = 8
```


```{r A13 hist}
a1<-ggplot(A13, aes(x=ED_per_used)) + geom_histogram(aes(x=ED_per_used, y=100 * (..count..)/sum(..count..))) + xlim(0,55) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),  title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Energy Used (%)", y="Percent", title="Columbia 2017, \nCWR Current") 
```

```{r B13 hist}
b1<-ggplot(B13, aes(x=ED_per_used)) + geom_histogram(aes(x=ED_per_used, y=100 * (..count..)/sum(..count..))) + xlim(0,55) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Energy Used (%)", y="Percent", title="Columbia 2017, \nNo CWR")
```

```{r C13 hist}
c1<-ggplot(C13, aes(x=ED_per_used)) + geom_histogram(aes(x=ED_per_used, y=100 * (..count..)/sum(..count..))) + xlim(0,55) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Energy Used (%)", y="Percent", title="Columbia 2040 (2017), \nCWR Current")
```

```{r D13 hist}
d1<-ggplot(D13, aes(x=ED_per_used)) + geom_histogram(aes(x=ED_per_used, y=100 * (..count..)/sum(..count..))) + xlim(0,55) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Energy Used (%)", y="Percent", title="Columbia 2040 (2017), \nNo CWR")
```

```{r plot energy hist together, fig.cap="Fig. 1. Histogram of percent energy lost for modeled Grande Ronde summer steelhead migrating through four different modeled thermalscapes."}
plot_grid( a1, b1, c1, d1, 
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2)
```


```{r energy lost boxplot, fig.cap="Fig. 2. Boxplot of percent energy lost for modeled Grande Ronde summer steelhead migrating through four different modeled thermalscapes."}
all_13$scenario<-as.factor(all_13$scenario)

out2<-ggplot(all_13, aes(x=scenario, y=ED_per_used, group=scenario)) +   
  geom_boxplot() + 
  labs( y="Energy lost (%)", title="Grande Ronde River Summer Steelhead") + 
  theme_classic() 

out2 + theme(axis.text.x=element_text(color = "black", size=11, angle=30, vjust=.8, hjust=0.8), axis.title.x=element_blank(),) + scale_x_discrete(limits=c("A", "B", "C","D"), labels=c(
  "Columbia 2017,\n CWR Current",
  "Columbia 2017, \nNo CWRs", 
  "Columbia 2040 (2017), \nCWR Current", 
  "Columbia 2040 (2017), \nNo CWRs")) 
```


```{r energy lost table}
ED_used_table<-aggregate(ED_per_used~scenario, data=all_13, quantile)
ED_used_table$scenario<-as.character(ED_used_table$scenario)
ED_used_table<-format(ED_used_table, digits = 2)
ED_used_table$scenario[ED_used_table$scenario == "A"] <- "Columbia 2017, CWR Current"
ED_used_table$scenario[ED_used_table$scenario == "B"] <- "Columbia 2017, No CWR"
ED_used_table$scenario[ED_used_table$scenario == "C"] <- "Columbia 2017, CWR Current"
ED_used_table$scenario[ED_used_table$scenario == "D"] <- "Columbia 2017, No CWR"


# create table with pretty format
kable(ED_used_table, col.names=c( "Scenario", "Minimum", "25% quantile","Median", "75% quantile", "Maximum"),row.names=FALSE, caption="Table 1. Percent energy used across different HexSim thermalscapes summarized for Grande Ronde River Summer Steelhead.", digits=1)
```


```{r import refuges data, eval=TRUE, echo=FALSE}
# import refuges population census table
# only has refuge density for hours when a refuge is occupied
# import in combined replicate DFs
A9<-read.table("D:/Results_4Populations/gr_Columbia2017B/combined/E9.csv", header=TRUE, sep=",")
B9<-read.table("D:/Results_4Populations/gr_Columbia2017B_NoCWR/combined/F9.csv", header=TRUE, sep=",")
C9<-read.table("D:/Results_4Populations/gr_Columbia2017BplusOne/combined/G9.csv", header=TRUE, sep=",")
D9<-read.table("D:/Results_4Populations/gr_Columbia2017BplusOne_NoCWR/combined/H9.csv", header=TRUE, sep=",")

# rename columns
colnames(A9)<-c("run","timestep","Population","ID", "refuge_id", "refuge_depth_chinook" ,"refuge_depth_steelhead", "effective_volume_chinook","effective_volume_steelhead", "current_refuge_density",
            "retain_chinook","retain_steelhead", "removed_chinook", "removed_steelhead")
colnames(B9)<-c("run","timestep","Population","ID", "refuge_id", "refuge_depth_chinook" ,"refuge_depth_steelhead", "effective_volume_chinook","effective_volume_steelhead", "current_refuge_density",
            "retain_chinook","retain_steelhead", "removed_chinook", "removed_steelhead")
colnames(C9)<-c("run","timestep","Population","ID", "refuge_id", "refuge_depth_chinook" ,"refuge_depth_steelhead", "effective_volume_chinook","effective_volume_steelhead", "current_refuge_density",
            "retain_chinook","retain_steelhead", "removed_chinook", "removed_steelhead")
colnames(D9)<-c("run","timestep","Population","ID", "refuge_id", "refuge_depth_chinook" ,"refuge_depth_steelhead", "effective_volume_chinook","effective_volume_steelhead", "current_refuge_density",
            "retain_chinook","retain_steelhead", "removed_chinook", "removed_steelhead")

# create dataframe to link hexsim refuge id with name of refuge
# HexSim Refuge ID in this file:
# 14 - Eagle Creek
# 15 - Rock Creek
# 16 - Herman Creek
# 17 - Wind River
# 18 - Little White Salmon River
# 19 - White Salmon River
# 20 - Klickitat River
# 21 - Deschutes River
# 22 - Umatilla River
# create sequence of refuge IDs
refuge_IDseq<-seq(14,22,1)
# create translator sequence because model adds 1 
#refuge_IDseq2<-seq(1,7,1)

# create vector of refuge names
refuge_name<-c("Eagle Creek", "Rock Creek", "Herman Creek", "Wind River", "Little White Salmon River","White Salmon River", "Klickitat River", "Deschutes River", "Umatilla River")
refuge_id<-cbind.data.frame(refuge_IDseq, refuge_name) # create dataframe to link refuge ID value with refuge Name
# merge name with refuge data
A9_2<-merge(A9, refuge_id, by.x="refuge_id", by.y="refuge_IDseq")
B9_2<-merge(B9, refuge_id, by.x="refuge_id", by.y="refuge_IDseq")
C9_2<-merge(C9, refuge_id, by.x="refuge_id", by.y="refuge_IDseq")
D9_2<-merge(D9, refuge_id, by.x="refuge_id", by.y="refuge_IDseq")

C_sum<-sum(C9_2$retain_steelhead)
A_sum<-sum(A9_2$retain_steelhead)
B_sum<-sum(B9_2$retain_steelhead)
D_sum<-sum(D9_2$retain_steelhead)
sum_v<-c(A_sum,B_sum, C_sum, D_sum)

names_v<-c("Columbia 2017,CWR Current",
  "Columbia 2017, No CWRs", 
  "Columbia 2040 (2017), Current", 
  "Columbia 2040 (2017), No CWRs")
refuge_use_all<-cbind(names_v, sum_v)
kable(refuge_use_all, col.names=c("Scenario", "Total CWR Residence (h)"), caption="Table 3. Model output for total hours residing n cold water refuges summarized for Grande Ronde River Summer Steelhead.")
```

```{r summarize dying fish}
# import in combined replicate DFs
A12<-read.table("D:/Results_4Populations/gr_Columbia2017B/combined/E12.csv", header=TRUE, sep=",")
B12<-read.table("D:/Results_4Populations/gr_Columbia2017B_NoCWR/combined/F12.csv", header=TRUE, sep=",")
C12<-read.table("D:/Results_4Populations/gr_Columbia2017BplusOne/combined/G12.csv", header=TRUE, sep=",")
D12<-read.table("D:/Results_4Populations/gr_Columbia2017BplusOne_NoCWR/combined/H12.csv", header=TRUE, sep=",")

# number of simulated fish
num_fish<-2000
# get number of individuals died from acute temperature stress
acute_A<-((dim(A12)[1])/ num_fish) * 100
acute_B<-((dim(B12)[1])/ num_fish) * 100
acute_C<-((dim(C12)[1])/ num_fish) * 100
acute_D<-((dim(D12)[1])/ num_fish) * 100

acute_v<-c( acute_A, acute_B, acute_C,  acute_D)
acute_all<-cbind(names_v, acute_v)
kable(acute_all, col.names=c("Scenario", "Total mortality"), caption="Table 4. Model output for percent of individuals dying from acute temperature stress summarized for Grande Ronde River Summer Steelhead.")

```



```{r time in system histogram}
all_13$Time_in_system_d<-all_13$Time_in_system / 24
all_13_labels<-all_13
# vector of scenario labels
all_13_labels$scenario<-as.factor(all_13_labels$scenario)
levels(all_13_labels$scenario)[levels(all_13_labels$scenario)=="A"] <-"Columbia 2017, CWR Current"
levels(all_13_labels$scenario)[levels(all_13_labels$scenario)=="B"] <-"Columbia 2017, No CWR"
levels(all_13_labels$scenario)[levels(all_13_labels$scenario)=="C"] <-"Columbia 2040 (2017), CWR Current"
levels(all_13_labels$scenario)[levels(all_13_labels$scenario)=="D"] <-"Columbia 2040 (2017), No CWR"


#v_names<-c("Columbia 2040- CWR Current", "Columbia Restored- CWR Current","Columbia Current- CWR Current", "Columbia #Current- CWR Restored", "Columbia 2040- No CWRs", "Columbia Restored- No CWRs","Columbia Current- No CWRs" )
p <- ggplot(data = all_13_labels, aes(x = Time_in_system_d)) + geom_histogram(binwidth = 5)
p + facet_wrap(~scenario) + labs(x="Passage time (d)", y="Count", title="Grande Ronde River Summer Steelhead")

```


```{r terminus arrival histogram preparation}
# model starts on July 1 which is equivalent to julian day 182
jday_start<-182

# step is hour arrived at terminus
# convert Step to julian day
all_13_labels$terminus_jday<-floor(all_13_labels$Step / 24) + jday_start
# convert julian day to date
all_13_labels$terminus_date_ch<-chron(all_13_labels$terminus_jday, origin=c(month=1, day=1, year=2019))
# convert date format to posixct
all_13_labels$terminus_date<- as.POSIXct(all_13_labels$terminus_date_ch, "GMT") 

# Time_entry is hour started from Bonneville
# convert Step to julian day
all_13_labels$entry_jday<-floor(all_13_labels$Time_entry / 24) + jday_start
# convert julian day to date
all_13_labels$entry_date_ch<-chron(all_13_labels$entry_jday, origin=c(month=1, day=1, year=2019))
# convert date format to posixct
all_13_labels$entry_date<- as.POSIXct(all_13_labels$entry_date_ch, "GMT") 
```

```{r terminus arrival histogram}
# histograms
p <- ggplot(data = all_13_labels, aes(x = terminus_date)) + geom_histogram()
p + facet_wrap(~scenario) + labs(x="Exit Day", y="Count", title="Grande Ronde River Summer Steelhead")

```


```{r import hourly, eval=TRUE}
# import in combined replicate DFs
E14<-fread("D:/Results_4Populations/gr_Columbia2017B/combined/E14.csv", header=TRUE, sep=",")
F14<-fread("D:/Results_4Populations/gr_Columbia2017B_NoCWR/combined/F14.csv", header=TRUE, sep=",")
G14<-fread("D:/Results_4Populations/gr_Columbia2017BplusOne/combined/G14.csv", header=TRUE, sep=",")
H14<-fread("D:/Results_4Populations/gr_Columbia2017BplusOne_NoCWR/combined/H14.csv", header=TRUE, sep=",")

# rename columns
names(E14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(F14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(G14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(H14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")

# add scenario designation
E14$scenario<-"Columbia 2017, CWR Current"
F14$scenario<-"Columbia 2017, No CWR"
G14$scenario<-"Columbia 2040 (2017), CWR Current"
H14$scenario<-"Columbia 2040 (2017), No CWR"

# create scenario factor for each scenario
E14$scenario<-as.factor(E14$scenario)
F14$scenario<-as.factor(F14$scenario)
G14$scenario<-as.factor(G14$scenario)
H14$scenario<-as.factor(H14$scenario)
  
# combine all
hourly_all<-rbind.data.frame(E14, F14, G14, H14)
# change to factor
hourly_all$scenario<-as.factor(hourly_all$scenario)
```

```{r calc mean temperature experienced from hourly}
mean_temp_E14<-aggregate(temp_1~ID, data=E14, mean)
mean_temp_F14<-aggregate(temp_1~ID, data=F14, mean)
mean_temp_G14<-aggregate(temp_1~ID, data=G14, mean)
mean_temp_H14<-aggregate(temp_1~ID, data=H14, mean)

```

```{r combine mean temp with end condition}
# subset end_condition all scenarios to one scenario
all_13_labels_A<-dplyr::filter(all_13_labels, scenario == "Columbia 2017, CWR Current")
# join with mean temp for scenario
hourly_and_end_A<-merge(all_13_labels_A, mean_temp_E14, by.x="ID", by.y="ID")
```


```{r A plot duration vs energy used}
dur1<-ggplot(hourly_and_end_A, aes(x=Time_in_system_d, y=ED_per_used, color=Total_hours_cold_water)) +   
  geom_point() + 
  labs( y="Energy lost (%)", x="Time migrating (d)", title="Grande Ronde River Summer Steelhead") + 
  theme_classic() + scale_color_gradient(name="Hours in Cold Water", low="blue", high="red")
```

```{r B plot duration vs energy used}
dur2<-ggplot(hourly_and_end_A, aes(x=Time_in_system_d, y=ED_per_used, color=temp_1)) +   
  geom_point() + 
  labs( y="Energy lost (%)", x="Time migrating (d)") + 
  theme_classic() + scale_color_gradient(name="Mean temperature", low="blue", high="red")
```

```{r C plot duration vs energy used}
dur3<-ggplot(hourly_and_end_A, aes(x=Time_in_system_d, y=ED_per_used, color=entry_jday)) +   
  geom_point() + 
  labs( y="Energy lost (%)", x="Time migrating (d)") + 
  theme_classic() + scale_color_gradient(name="Entry date", low="blue", high="red")
```

```{r D plot duration vs energy used}
dur4<-ggplot(hourly_and_end_A, aes(x=Time_in_system_d, y=ED_per_used, color=terminus_jday)) +   
  geom_point() + 
  labs( y="Energy lost (%)", x="Time migrating (d)") + 
  theme_classic() + scale_color_gradient(name="Exit date", low="blue", high="red")
```

```{r plot formatting 2}
width1 = 4.5
height1 = 7
text1 = 8
```

```{r plot energy lost scatter plots together, fig.height = 7, fig.width = 6, fig.cap="Fig. 5. Plots of percent energy lost versus the number of days spent migrating from Bonneville to confluence with Snake River for Grande Ronde River summer steelhead. Colors represent A. total hours spent residing in cold water refuges, B. mean temperature experienced during migration, C. start date for migration in julian days, and D. julian date of arrival at Snake River confluence."}
plot_grid( dur1, dur2, dur3, dur4, 
          labels = c("A", "B", "C", "D"),align="v",
          ncol = 1, nrow = 4)
```

```{r add refuge or mainstem identifier to hourly for plot}
E14$location<-"Columbia"
E14$location[E14$refuge_id > 5]<-"Refuge"
```


```{r add date column to hourly data}
# convert Step to julian day
E14$step_jday<-floor(E14$Step / 24) + jday_start
# convert julian day to date
E14$step_date_ch<-chron(E14$step_jday, origin=c(month=1, day=1, year=2019))
# convert date format to posixct
E14$step_date<- as.POSIXct(E14$step_date_ch, "GMT") 

```

```{r add refuge name column to hourly data}
# refuge_name2<-c("Below Bonneville Dam", "Bonneville Pool", "The Dalles Pool", "John Day Pool", "Above McNary", "Skamokawa Creek", "Skamokawa Plume", "Mill Creek", "Abernethy Creek", "Abernethy Plume", "Germany Creek", "Cowlitz River", "Cowlitz Plume", "Kalama River", "Kalama Plume", "Lewis River", "Lewis Plume", "Sandy River", "Sandy Plume", "Washougal River", "Washougal Plume", "Bridal Veil Creek", "Bridal Veil Plume", "Wahkeena Creek", "Oneonta Creek", "Oneonta Plume", "Tanner Creek", "Tanner Plume", "Eagle Creek", "Eagle Plume", "Rock Creek", "Rock Plume", "Herman Creek ", "Herman Plume", "Wind River", "Wind Plume", "Little White Salmon River", "Little White Salmon Plume", "White Salmon River", "White Salmon Plume", "Klickitat River", "Klickitat Plume", "Deschutes River", "Deschutes Plume", "Umatilla River")

refuge_name2<-c("Below Bonneville Dam", "Bonneville Pool", "The Dalles Pool", "John Day Pool", "Above McNary", "Skamokawa", "Skamokawa", "Mill", "Abernethy", "Abernethy", "Germany", "Cowlitz", "Cowlitz", "Kalama", "Kalama", "Lewis", "Lewis", "Sandy", "Sandy", "Washougal", "Washougal", "Bridal Veil", "Bridal Veil", "Wahkeena", "Oneonta", "Oneonta", "Tanner", "Tanner", "Eagle", "Eagle", "Rock", "Rock", "Herman", "Herman", "Wind", "Wind", "Little White Salmon", "Little White Salmon", "White Salmon", "White Salmon", "Klickitat", "Klickitat", "Deschutes", "Deschutes", "Umatilla")

refuge_name2_seq<-seq(1,45,1)

refuges_and_refuge_IDs<-cbind.data.frame(refuge_name2_seq, refuge_name2)

# all hourly with thermal patch name combine and plot
E14<-merge(E14, refuges_and_refuge_IDs, by.x="refuge_id", by.y="refuge_name2_seq")
```


```{r select some winners}
gr_winners<-dplyr::filter(hourly_and_end_A, ED_per_used < 20 & ED_per_used > 19.75 )
dim(gr_winners)

# create column for include
gr_winners$winner_yes<-"y"
# select 10 winners from hourly data
E14$ID<-as.factor(E14$ID)
# drop all columns except ID and winner flag
gr_winners<-dplyr::select(gr_winners, "ID", "winner_yes")
# merge winner DF with hourly
E14_winners<-merge(E14, gr_winners, by.x="ID", by.y="ID")
# drop unused factor levels
E14_winners$refuge_name2.y<-as.factor(E14_winners$refuge_name2.y)
```

```{r select some losers}
gr_losers<-dplyr::filter(hourly_and_end_A, ED_per_used > 41.5 & ED_per_used < 42)
dim(gr_losers)
# create column for include
gr_losers$losers_yes<-"y"
# select 10 losers from hourly data
E14$ID<-as.factor(E14$ID)
# drop all columns except ID and winner flag
gr_losers<-dplyr::select(gr_losers, "ID", "losers_yes")
# merge winner DF with hourly
E14_losers<-merge(E14, gr_losers, by.x="ID", by.y="ID")
# drop unused factor levels
E14_losers$refuge_name2.y<-as.factor(E14_losers$refuge_name2.y)
```

```{r plot limits 1}
xaxis1<-"2019-07-01 17:00:00"
xaxis2<-"2019-11-01 17:00:00"
yaxis1<-5000
yaxis2<-12000
```

```{r plot winners 1}
step_refuge_win<-ggplot(E14_winners, aes(x=step_date, y=energy, color=location)) +   
  geom_point() + xlim( as.POSIXct("2019-07-01 17:00:00"), as.POSIXct("2019-11-01 17:00:00")) + ylim(yaxis1,yaxis2) +
  labs( y="Energy", x="Date", title="Winners", color="Location") + 
  theme_classic() +  scale_color_manual(values=c("darkred", "blue4"))

#step_refuge_win 
```

```{r plot losers 1}
step_refuge_loser<-ggplot(E14_losers, aes(x=step_date, y=energy, color=location)) +   
  geom_point() + xlim( as.POSIXct("2019-07-01 17:00:00"), as.POSIXct("2019-11-01 17:00:00")) + ylim(yaxis1,yaxis2) +
  labs( y="Energy", x="Date", title="Losers", color="Location") + 
  theme_classic()  +  scale_color_manual(values=c("darkred", "blue4"))

#step_refuge_loser
```

```{r plot winners and losers 1, fig.height = 8, fig.width = 6, fig.cap="Fig. 6. "}
plot_grid( step_refuge_win, step_refuge_loser, 
          labels = c("A", "B"),align="v",
          ncol = 1, nrow = 2)
```

```{r plot limits 2}
xaxis1<-"2019-07-01 17:00:00"
xaxis2<-"2019-11-01 17:00:00"
yaxis1<-5000
yaxis2<-12000
```


```{r plot winners 2}
step_temp_win<-ggplot(E14_winners, aes(x=step_date, y=energy, colour=temp_1 )) +   
  geom_point() + xlim( as.POSIXct("2019-07-01 17:00:00"), as.POSIXct("2019-11-01 17:00:00")) + ylim(yaxis1,yaxis2) +
  labs( y="Energy", x="Date", title="Winners", color="Temperature") + scale_color_gradient(high="red", low="blue", limits=c(5,25)) + theme_classic()

#step_temp_win 
```

```{r plot losers 2}
step_temp_loser<-ggplot(E14_losers, aes(x=step_date, y=energy, colour=temp_1)) +   
  geom_point() + xlim( as.POSIXct("2019-07-01 17:00:00"), as.POSIXct("2019-11-01 17:00:00")) + ylim(yaxis1,yaxis2) +
  labs( y="Energy", x="Date", title="Losers", color="Temperature") + scale_color_gradient(high="red", low="blue", limits=c(5,25)) + theme_classic()

#step_temp_loser
```

```{r plot winners and losers 2, fig.height = 8, fig.width = 6, fig.cap="Fig. 7. "}
plot_grid( step_temp_win, step_temp_loser, 
          labels = c("A", "B"),align="v",
          ncol = 1, nrow = 2)
```


```{r plot limits 3}
xaxis1<-"2019-07-01 17:00:00"
xaxis2<-"2019-11-01 17:00:00"
yaxis1<-5
yaxis2<-25
```


```{r plot winners 3}
step_temp_win2<-ggplot(E14_winners, aes(x=step_date, y=temp_1, color=ID)) +   
  geom_point() + xlim( as.POSIXct("2019-07-01 17:00:00"), as.POSIXct("2019-11-01 17:00:00")) + ylim(yaxis1,yaxis2) +
  labs( y="Temperature", x="Date", title="Winners", color="ID") + 
  theme_classic() + theme(legend.position = "none")

#step_temp_win2
```

```{r plot losers 3}
step_temp_loser2<-ggplot(E14_losers, aes(x=step_date, y=temp_1, color=ID)) +   
  geom_point() + xlim( as.POSIXct("2019-07-01 17:00:00"), as.POSIXct("2019-11-01 17:00:00")) + ylim(yaxis1,yaxis2) +
  labs( y="Temperature", x="Date", title="Losers", color="ID") + 
  theme_classic()  + theme(legend.position = "none")


#step_temp_loser2
```

```{r plot winners and losers 3, fig.height = 8, fig.width = 6, fig.cap="Fig. 8. "}
plot_grid( step_temp_win2, step_temp_loser2, 
          labels = c("A", "B"),align="v",
          ncol = 1, nrow = 2)
```

```{r plot limits 4}
xaxis1<-"2019-07-01 17:00:00"
xaxis2<-"2019-11-01 17:00:00"
yaxis1<-5000
yaxis2<-12000
```

summary(E14_winners$refuge_name2.y)
```{r plot winners 4}

step_refuge_win2<-ggplot(E14_winners, aes(x=step_date, y=energy, color=refuge_name2.y)) +   
  geom_point() + xlim( as.POSIXct("2019-07-01 17:00:00"), as.POSIXct("2019-11-01 17:00:00")) + ylim(yaxis1,yaxis2) +
  labs( y="Energy", x="Date", title="Winners", color="Location") + 
  theme_classic() +  scale_color_manual(values=c("brown4", "brown1", "aquamarine", "gold1", "blue", "brown3", "cyan4", "darkorchid1",  "brown2", "darkblue", "green")) + 
  guides(colour = guide_legend(override.aes = list(size = 6)))

#step_refuge_win2 
```

summary(E14_losers$refuge_name2.y)
```{r plot losers 4}
step_refuge_loser2<-ggplot(E14_losers, aes(x=step_date, y=energy, color=refuge_name2.y)) +   
  geom_point() + xlim( as.POSIXct("2019-07-01 17:00:00"), as.POSIXct("2019-11-01 17:00:00")) + ylim(yaxis1,yaxis2) +
  labs( y="Energy", x="Date", title="Losers", color="Location") + 
  theme_classic()  +  scale_color_manual(values=c("brown4", "brown1", "aquamarine", "gold1",  "brown3", "cyan4", "darkorchid1",  "brown2", "darkblue","orange", "green")) + 
  guides(colour = guide_legend(override.aes = list(size = 6)))


#step_refuge_loser2
```

```{r plot winners and losers 4, fig.height = 8, fig.width = 6, fig.cap="Fig. 9. "}
plot_grid( step_refuge_win2, step_refuge_loser2, 
          labels = c("A", "B"),align="v",
          ncol = 1, nrow = 2)
```

