---
title: "Grande Ronde summer steelhead cumulative DD"
author: "MNSnyder"
date: "8/29/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
library(ggplot2)
library(cowplot)
library(data.table)
library(knitr)
library(chron)
```


```{r plot formatting}
width1 = 4.5
height1 = 3.5
text1 = 8
```

```{r import hourly}
# import in combined replicate DFs
A14<-fread("D:/Results_4Populations/gr_Columbia2040_current/combined/A14.csv", header=TRUE, sep=",")
B14<-fread("D:/Results_4Populations/gr_Columbiarestored_CWRcurrent/combined/B14.csv", header=TRUE, sep=",")
C14<-fread("D:/Results_4Populations/gr_current_current/combined/C14.csv", header=TRUE, sep=",")
D14<-fread("D:/Results_4Populations/gr_current_restoredCWR/combined/D14.csv", header=TRUE, sep=",")
E14<-fread("D:/Results_4Populations/gr_Columbia2040_No_CWR/combined/E14.csv", header=TRUE, sep=",")
F14<-fread("D:/Results_4Populations/gr_Columbiarestored_No_CWR/combined/F14.csv", header=TRUE, sep=",")
G14<-fread("D:/Results_4Populations/gr_current_current_No_CWR/combined/G14.csv", header=TRUE, sep=",")

# rename columns
names(A14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(B14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(C14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(D14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(E14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(F14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(G14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")

```

## DD > 18 °C
```{r calc DD GT 18 for each scenario}
# function to calculate cumulative degree days above a certain degree
dum_dd<-function(threshold, DF){
  DF_subset<-DF[which(DF$temp_1 >= threshold),]
  dd_threshold<-aggregate(temp_1~ID, data=DF_subset, sum)
  dd_threshold$temp_1<-dd_threshold$temp_1/24
  return(dd_threshold)
}

# set threshold
thres<-18
# run for each scenario's hourly DF
A14_ddGT18<-dum_dd(thres, A14)
B14_ddGT18<-dum_dd(thres, B14)
C14_ddGT18<-dum_dd(thres, C14)
D14_ddGT18<-dum_dd(thres, D14)
E14_ddGT18<-dum_dd(thres, E14)
F14_ddGT18<-dum_dd(thres, F14)
G14_ddGT18<-dum_dd(thres, G14)
# add scenario column
A14_ddGT18$scenario<-"A"
B14_ddGT18$scenario<-"B"
C14_ddGT18$scenario<-"C"
D14_ddGT18$scenario<-"D"
E14_ddGT18$scenario<-"E"
F14_ddGT18$scenario<-"F"
G14_ddGT18$scenario<-"G"

#combine
all_14_ddGT18<-rbind.data.frame(A14_ddGT18, B14_ddGT18, C14_ddGT18, D14_ddGT18, E14_ddGT18, F14_ddGT18,G14_ddGT18)

```


```{r A14 hist}
a2<-ggplot(A14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia 2040, \nCWR Current") 
```

```{r B14 hist}
b2<-ggplot(B14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia Restored, \nCWR Current")
```

```{r C14 hist}
c2<-ggplot(C14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia Current, \nCWR Current")
```

```{r D14 hist}
d2<-ggplot(D14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia Current, \nCWR Restored")
```

```{r E14 hist}
e2<-ggplot(E14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia 2040, \nNo CWRs")
```

```{r F14 hist}
f2<-ggplot(F14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia Restored, \nNo CWRs")
```

```{r G14 hist}
g2<-ggplot(G14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia Current, \nNo CWRs")
```

```{r plot DD hist together, fig.cap="Fig. 1. Histograms of modeled Grande Ronde River summer steelhead accumulated degrees day over 18°C from Bonneville to the Snake River confluence in the Columbia River."}
plot_grid(c2, a2, b2, d2, g2, e2, f2,
          labels = c("A", "B", "C", "D", "E", "F", "G"),
          ncol = 3, nrow = 3)
```

```{r cum DD boxplot, fig.cap="Fig. 2. Boxplots of modeled Grande Ronde River summer steelhead accumulated degrees day over 18°C from Bonneville to the Snake River confluence in the Columbia River."}
all_14_ddGT18$scenario<-as.factor(all_14_ddGT18$scenario)

out3<-ggplot(all_14_ddGT18, aes(x=scenario, y=temp_1, group=scenario)) +   
  geom_boxplot() + 
  labs( y="Cumulative degree days (>18°C)", title="Grande Ronde River Summer Steelhead") + 
  theme_classic() 

out3 + theme(axis.text.x=element_text(color = "black", size=11, angle=30, vjust=.8, hjust=0.8), axis.title.x=element_blank(),) + scale_x_discrete(limits=c("C","G", "A","E", "B", "F","D"), labels=c(
  "Columbia Current,\n CWR Current",
  "Columbia Current, \nNo CWRs", 
  "Columbia 2040, \nCWR Current", 
  "Columbia 2040, \nNo CWRs", 
 "Columbia Restored, \nCWR Current", 
 "Columbia Restored, \nNo CWRs",
  "Columbia Current, \nCWR Restored")) 
```

```{r DD lost table}
DD_used_table<-aggregate(temp_1~scenario, data=all_14_ddGT18, quantile)
DD_used_table$scenario<-as.character(DD_used_table$scenario)
DD_used_table<-format(DD_used_table, digits = 0) # round 

DD_used_table$scenario[DD_used_table$scenario == "A"] <- "Columbia 2040, CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "B"] <- "Columbia Restored, CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "C"] <- "Columbia Current, CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "D"] <- "Columbia Current, CWR Restored"
DD_used_table$scenario[DD_used_table$scenario == "E"] <- "Columbia 2040, No CWRs"
DD_used_table$scenario[DD_used_table$scenario == "F"] <- "Columbia Restored, No CWRs"
DD_used_table$scenario[DD_used_table$scenario == "G"] <- "Columbia Current, No CWRs"
# create table with pretty format
kable(DD_used_table, col.names=c( "Scenario", "Minimum", "25% quantile","Median", "75% quantile", "Maximum"),row.names=FALSE, caption="Table 1. Cumulative degree days (>18°C) used across different HexSim thermalscapes summarized for Grande Ronde River Summer Steelhead.", digits=1)
```

###################################################################
## Degree Days > 20°C

```{r calc DD GT 20 for each scenario}
# function to calculate cumulative degree days above a certain degree
dum_dd<-function(threshold, DF){
  DF_subset<-DF[which(DF$temp_1 >=threshold),]
  dd_threshold<-aggregate(temp_1~ID, data=DF_subset, sum)
  dd_threshold$temp_1<-dd_threshold$temp_1/24
  return(dd_threshold)
}

# set threshold
thres<-20
# run for each scenario's hourly DF
A14_ddGT18<-dum_dd(thres, A14)
B14_ddGT18<-dum_dd(thres, B14)
C14_ddGT18<-dum_dd(thres, C14)
D14_ddGT18<-dum_dd(thres, D14)
E14_ddGT18<-dum_dd(thres, E14)
F14_ddGT18<-dum_dd(thres, F14)
G14_ddGT18<-dum_dd(thres, G14)
# add scenario column
A14_ddGT18$scenario<-"A"
B14_ddGT18$scenario<-"B"
C14_ddGT18$scenario<-"C"
D14_ddGT18$scenario<-"D"
E14_ddGT18$scenario<-"E"
F14_ddGT18$scenario<-"F"
G14_ddGT18$scenario<-"G"

#combine
all_14_ddGT18<-rbind.data.frame(A14_ddGT18, B14_ddGT18, C14_ddGT18, D14_ddGT18, E14_ddGT18, F14_ddGT18,G14_ddGT18)

```


```{r A14 hist 20}
a2<-ggplot(A14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>20°C)", y="Percent", title="Columbia 2040, \nCWR Current") 
```

```{r B14 hist 20}
b2<-ggplot(B14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>20°C)", y="Percent", title="Columbia Restored, \nCWR Current")
```

```{r C14 hist 20}
c2<-ggplot(C14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>20°C)", y="Percent", title="Columbia Current, \nCWR Current")
```

```{r D14 hist 20}
d2<-ggplot(D14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>20°C)", y="Percent", title="Columbia Current, \nCWR Restored")
```

```{r E14 hist 20}
e2<-ggplot(E14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>20°C)", y="Percent", title="Columbia 2040, \nNo CWRs")
```

```{r F14 hist 20}
f2<-ggplot(F14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>20°C)", y="Percent", title="Columbia Restored, \nNo CWRs")
```

```{r G14 hist 20}
g2<-ggplot(G14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>20°C)", y="Percent", title="Columbia Current, \nNo CWRs")
```

```{r plot DD hist together 20, fig.cap="Fig. 3. Histograms of modeled Grande Ronde River summer steelhead accumulated degrees day over 20°C from Bonneville to the Snake River confluence in the Columbia River."}
plot_grid(c2, a2, b2, d2, g2, e2, f2,
          labels = c("A", "B", "C", "D", "E", "F", "G"),
          ncol = 3, nrow = 3)
```

```{r cum DD boxplot 20, fig.cap="Fig. 4. Boxplots of modeled Grande Ronde River summer steelhead accumulated degrees day over 20°C from Bonneville to the Snake River confluence in the Columbia River."}
all_14_ddGT18$scenario<-as.factor(all_14_ddGT18$scenario)

out3<-ggplot(all_14_ddGT18, aes(x=scenario, y=temp_1, group=scenario)) +   
  geom_boxplot() + 
  labs( y="Cumulative degree days (>20°C)", title="Grande Ronde River Summer Steelhead") + 
  theme_classic() 

out3 + theme(axis.text.x=element_text(color = "black", size=11, angle=30, vjust=.8, hjust=0.8), axis.title.x=element_blank(),) + scale_x_discrete(limits=c("C","G", "A","E", "B", "F","D"), labels=c(
  "Columbia Current,\n CWR Current",
  "Columbia Current, \nNo CWRs", 
  "Columbia 2040, \nCWR Current", 
  "Columbia 2040, \nNo CWRs", 
 "Columbia Restored, \nCWR Current", 
 "Columbia Restored, \nNo CWRs",
  "Columbia Current, \nCWR Restored")) 
```

```{r DD lost table 20}
DD_used_table<-aggregate(temp_1~scenario, data=all_14_ddGT18, quantile)
DD_used_table$scenario<-as.character(DD_used_table$scenario)
DD_used_table<-format(DD_used_table, digits = 0) # round 

DD_used_table$scenario[DD_used_table$scenario == "A"] <- "Columbia 2040, CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "B"] <- "Columbia Restored, CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "C"] <- "Columbia Current, CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "D"] <- "Columbia Current, CWR Restored"
DD_used_table$scenario[DD_used_table$scenario == "E"] <- "Columbia 2040, No CWRs"
DD_used_table$scenario[DD_used_table$scenario == "F"] <- "Columbia Restored, No CWRs"
DD_used_table$scenario[DD_used_table$scenario == "G"] <- "Columbia Current, No CWRs"
# create table with pretty format
kable(DD_used_table, col.names=c( "Scenario", "Minimum", "25% quantile","Median", "75% quantile", "Maximum"),row.names=FALSE, caption="Table 2. Cumulative degree days (>20°C) used across different HexSim thermalscapes summarized for Grande Ronde River Summer Steelhead.", digits=1)
```


###################################################################
## Degree Days > 21°C

```{r calc DD GT 21 for each scenario}
# function to calculate cumulative degree days above a certain degree
dum_dd<-function(threshold, DF){
  DF_subset<-DF[which(DF$temp_1 >=threshold),]
  dd_threshold<-aggregate(temp_1~ID, data=DF_subset, sum)
  dd_threshold$temp_1<-dd_threshold$temp_1/24
  return(dd_threshold)
}

# set threshold
thres<-21
# run for each scenario's hourly DF
A14_ddGT18<-dum_dd(thres, A14)
#B14_ddGT18<-dum_dd(thres, B14)
C14_ddGT18<-dum_dd(thres, C14)
D14_ddGT18<-dum_dd(thres, D14)
E14_ddGT18<-dum_dd(thres, E14)
#F14_ddGT18<-dum_dd(thres, F14)
G14_ddGT18<-dum_dd(thres, G14)
# add scenario column
A14_ddGT18$scenario<-"A"
#B14_ddGT18$scenario<-"B"
C14_ddGT18$scenario<-"C"
D14_ddGT18$scenario<-"D"
E14_ddGT18$scenario<-"E"
#F14_ddGT18$scenario<-"F"
G14_ddGT18$scenario<-"G"

#combine
#all_14_ddGT18<-rbind.data.frame(A14_ddGT18, B14_ddGT18, C14_ddGT18, D14_ddGT18, E14_ddGT18, F14_ddGT18,G14_ddGT18)
all_14_ddGT18<-rbind.data.frame(A14_ddGT18, C14_ddGT18, D14_ddGT18, E14_ddGT18, G14_ddGT18)

```


```{r A14 hist 21}
a2<-ggplot(A14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>21°C)", y="Percent", title="Columbia 2040, \nCWR Current") 
```

```{r B14 hist 21, eval=FALSE}
b2<-ggplot(B14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>21°C)", y="Percent", title="Columbia Restored, \nCWR Current")
```

```{r C14 hist 21}
c2<-ggplot(C14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>21°C)", y="Percent", title="Columbia Current, \nCWR Current")
```

```{r D14 hist 21}
d2<-ggplot(D14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia Current, \nCWR Restored")
```

```{r E14 hist 21}
e2<-ggplot(E14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>21°C)", y="Percent", title="Columbia 2040, \nNo CWRs")
```

```{r F14 hist 21, eval=FALSE}
f2<-ggplot(F14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>21°C)", y="Percent", title="Columbia Restored, \nNo CWRs")
```

```{r G14 hist 21}
g2<-ggplot(G14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>21°C)", y="Percent", title="Columbia Current, \nNo CWRs")
```

```{r plot DD hist together 21, fig.cap="Fig. 5. Histograms of modeled Grande Ronde River summer steelhead accumulated degrees day over 21°C from Bonneville to the Snake River confluence in the Columbia River."}
plot_grid(c2, a2, d2, g2, e2,
          labels = c("A", "B", "C", "D", "E"),
          ncol = 3, nrow = 2)
```

```{r cum DD boxplot 21, fig.cap="Fig. 6. Boxplots of modeled Grande Ronde River summer steelhead accumulated degrees day over 21°C from Bonneville to the Snake River confluence in the Columbia River."}
all_14_ddGT18$scenario<-as.factor(all_14_ddGT18$scenario)

out3<-ggplot(all_14_ddGT18, aes(x=scenario, y=temp_1, group=scenario)) +   
  geom_boxplot() + ylim(0,800) +
  labs( y="Cumulative degree days (>21°C)", title="Grande Ronde River Summer Steelhead") + 
  theme_classic() 

out3 + theme(axis.text.x=element_text(color = "black", size=11, angle=30, vjust=.8, hjust=0.8), axis.title.x=element_blank(),) + scale_x_discrete(limits=c("C","G", "A","E", "D"), labels=c(
  "Columbia Current,\n CWR Current",
  "Columbia Current, \nNo CWRs", 
  "Columbia 2040, \nCWR Current", 
  "Columbia 2040, \nNo CWRs", 
  "Columbia Current, \nCWR Restored")) 
```

```{r DD lost table 21}
DD_used_table<-aggregate(temp_1~scenario, data=all_14_ddGT18, quantile)
DD_used_table$scenario<-as.character(DD_used_table$scenario)
DD_used_table<-format(DD_used_table, digits = 0) # round 

DD_used_table$scenario[DD_used_table$scenario == "A"] <- "Columbia 2040, CWR Current"
#DD_used_table$scenario[DD_used_table$scenario == "B"] <- "Columbia Restored, CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "C"] <- "Columbia Current, CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "D"] <- "Columbia Current, CWR Restored"
DD_used_table$scenario[DD_used_table$scenario == "E"] <- "Columbia 2040, No CWRs"
#DD_used_table$scenario[DD_used_table$scenario == "F"] <- "Columbia Restored, No CWRs"
DD_used_table$scenario[DD_used_table$scenario == "G"] <- "Columbia Current, No CWRs"
# create table with pretty format
kable(DD_used_table, col.names=c( "Scenario", "Minimum", "25% quantile","Median", "75% quantile", "Maximum"),row.names=FALSE, caption="Table 3. Cumulative degree days (>21°C) used across different HexSim thermalscapes summarized for Grande Ronde River Summer Steelhead.", digits=1)
```



