---
title: "Grande Ronde summer steelhead summarized fitness outcomes"
author: "MNSnyder"
date: "8/30/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
library(ggplot2)
library(cowplot)
library(data.table)
library(knitr)
library(chron)
library(tidyverse)
```


```{r import end condition}
# import in combined replicate DFs
A13<-read.table("D:/Results_4Populations/gr_Columbia2040_current/combined/A13.csv", header=TRUE, sep=",")
B13<-read.table("D:/Results_4Populations/gr_Columbiarestored_CWRcurrent/combined/B13.csv", header=TRUE, sep=",")
C13<-read.table("D:/Results_4Populations/gr_current_current/combined/C13.csv", header=TRUE, sep=",")
D13<-read.table("D:/Results_4Populations/gr_current_restoredCWR/combined/D13.csv", header=TRUE, sep=",")
E13<-read.table("D:/Results_4Populations/gr_Columbia2040_No_CWR/combined/E13.csv", header=TRUE, sep=",")
F13<-read.table("D:/Results_4Populations/gr_Columbiarestored_No_CWR/combined/F13.csv", header=TRUE, sep=",")
G13<-read.table("D:/Results_4Populations/gr_current_current_No_CWR/combined/G13.csv", header=TRUE, sep=",")

# rename DF columns
names(A13)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")
names(B13)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")
names(C13)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")
names(D13)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")
names(E13)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")
names(F13)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")
names(G13)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")

```


```{r created energy used for all scenarios without gamete}
# function to calculate cumulative degree days above a certain degree
avail_energy_diff<-function(DF){
  DF$gamete<-(((7598 + (0.527 * DF$Initial_weight)) * DF$Initial_weight) * 0.068) / DF$Initial_weight
DF$initial_ED_avail<-DF$Initial_energy_density-DF$gamete
# create column of energy lost
# energy_all$energy_lost<-energy_all$X11 - energy_all$X13
DF$energy_lost_gamete<-(DF$initial_ED_avail - DF$Fitness_energy) 
DF$ED_per_used<-(DF$energy_lost_gamete/DF$initial_ED_avail) * 100
return(DF)
}

A13<-avail_energy_diff(A13)
B13<-avail_energy_diff(B13)
C13<-avail_energy_diff(C13)
D13<-avail_energy_diff(D13)
E13<-avail_energy_diff(E13)
F13<-avail_energy_diff(F13)
G13<-avail_energy_diff(G13)

# add scenario identifying column
A13$scenario<-"A"
B13$scenario<-"B"
C13$scenario<-"C"
D13$scenario<-"D"
E13$scenario<-"E"
F13$scenario<-"F"
G13$scenario<-"G"
# combine DFs 
all_13<-rbind.data.frame(A13, B13, C13, D13, E13, F13, G13)
```


```{r created energy used for all scenarios, eval=FALSE, include=FALSE}
# A13$energy_density_used<-A13$Initial_energy_density-A13$Fitness_energy_density
# A13$ED_per_used<-(A13$energy_density_used / A13$Initial_energy_density) * 100
# A13$scenario<-"A"
# 
# B13$energy_density_used<-B13$Initial_energy_density-B13$Fitness_energy_density
# B13$ED_per_used<-(B13$energy_density_used / B13$Initial_energy_density) * 100
# B13$scenario<-"B"
# 
# C13$energy_density_used<-C13$Initial_energy_density-C13$Fitness_energy_density
# C13$ED_per_used<-(C13$energy_density_used / C13$Initial_energy_density) * 100
# C13$scenario<-"C"
# 
# D13$energy_density_used<-D13$Initial_energy_density-D13$Fitness_energy_density
# D13$ED_per_used<-(D13$energy_density_used / D13$Initial_energy_density) * 100
# D13$scenario<-"D"
# 
# E13$energy_density_used<-E13$Initial_energy_density-E13$Fitness_energy_density
# E13$ED_per_used<-(E13$energy_density_used / E13$Initial_energy_density) * 100
# E13$scenario<-"E"
# 
# F13$energy_density_used<-F13$Initial_energy_density-F13$Fitness_energy_density
# F13$ED_per_used<-(F13$energy_density_used / F13$Initial_energy_density) * 100
# F13$scenario<-"F"
# 
# G13$energy_density_used<-G13$Initial_energy_density-G13$Fitness_energy_density
# G13$ED_per_used<-(G13$energy_density_used / G13$Initial_energy_density) * 100
# G13$scenario<-"G"
# 
# all_13<-rbind.data.frame(A13, B13, C13, D13, E13, F13, G13)
```

```{r plot formatting}
width1 = 4.5
height1 = 3.5
text1 = 8
```


```{r A13 hist}
a1<-ggplot(A13, aes(x=ED_per_used)) + geom_histogram(aes(x=ED_per_used, y=100 * (..count..)/sum(..count..))) + xlim(0,50) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),  title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Energy Used (%)", y="Percent", title="Columbia 2040, \nCWR Current") 
```

```{r B13 hist}
b1<-ggplot(B13, aes(x=ED_per_used)) + geom_histogram(aes(x=ED_per_used, y=100 * (..count..)/sum(..count..))) + xlim(0,50) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Energy Used (%)", y="Percent", title="Columbia Restored, \nCWR Current")
```

```{r C13 hist}
c1<-ggplot(C13, aes(x=ED_per_used)) + geom_histogram(aes(x=ED_per_used, y=100 * (..count..)/sum(..count..))) + xlim(0,50) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Energy Used (%)", y="Percent", title="Columbia Current, \nCWR Current")
```

```{r D13 hist}
d1<-ggplot(D13, aes(x=ED_per_used)) + geom_histogram(aes(x=ED_per_used, y=100 * (..count..)/sum(..count..))) + xlim(0,50) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Energy Used (%)", y="Percent", title="Columbia Current, \nCWR Restored")
```

```{r E13 hist}
e1<-ggplot(E13, aes(x=ED_per_used)) + geom_histogram(aes(x=ED_per_used, y=100 * (..count..)/sum(..count..))) + xlim(0,50) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Energy Used (%)", y="Percent", title="Columbia 2040, \nNo CWRs")
```

```{r F13 hist}
f1<-ggplot(F13, aes(x=ED_per_used)) + geom_histogram(aes(x=ED_per_used, y=100 * (..count..)/sum(..count..))) + xlim(0,50) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Energy Used (%)", y="Percent", title="Columbia Restored, \nNo CWRs")
```

```{r G13 hist}
g1<-ggplot(G13, aes(x=ED_per_used)) + geom_histogram(aes(x=ED_per_used, y=100 * (..count..)/sum(..count..))) + xlim(0,50) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Energy Used (%)", y="Percent", title="Columbia Current, \nNo CWRs")
```

```{r plot energy hist together, fig.cap="Fig. 1. Histogram of percent energy lost for modeled Grande Ronde summer steelhead migrating through four different modeled thermalscapes."}
plot_grid(c1, a1, b1,  d1, g1,e1, f1, 
          labels = c("A", "B", "C", "D", "E","F", "G" ),
          ncol = 3, nrow = 3)
```


```{r energy lost boxplot, fig.cap="Fig. 2. Boxplot of percent energy lost for modeled Grande Ronde summer steelhead migrating through four different modeled thermalscapes."}
all_13$scenario<-as.factor(all_13$scenario)

out2<-ggplot(all_13, aes(x=scenario, y=ED_per_used, group=scenario)) +   
  geom_boxplot() + 
  labs( y="Energy lost (%)", title="Grande Ronde River Summer Steelhead") + 
  theme_classic() 

out2 + theme(axis.text.x=element_text(color = "black", size=11, angle=30, vjust=.8, hjust=0.8), axis.title.x=element_blank(),) + scale_x_discrete(limits=c("C","G", "A","E", "B", "F","D"), labels=c(
  "Columbia Current,\n CWR Current",
  "Columbia Current, \nNo CWRs", 
  "Columbia 2040, \nCWR Current", 
  "Columbia 2040, \nNo CWRs", 
 "Columbia Restored, \nCWR Current", 
 "Columbia Restored, \nNo CWRs",
  "Columbia Current, \nCWR Restored")) 
```


```{r energy lost table}
ED_used_table<-aggregate(ED_per_used~scenario, data=all_13, quantile)
ED_used_table$scenario<-as.character(ED_used_table$scenario)
ED_used_table<-format(ED_used_table, digits = 2)
ED_used_table$scenario[ED_used_table$scenario == "A"] <- "Columbia 2040, CWR Current"
ED_used_table$scenario[ED_used_table$scenario == "B"] <- "Columbia Restored, CWR Current"
ED_used_table$scenario[ED_used_table$scenario == "C"] <- "Columbia Current, CWR Current"
ED_used_table$scenario[ED_used_table$scenario == "D"] <- "Columbia Current, CWR Restored"
ED_used_table$scenario[ED_used_table$scenario == "E"] <- "Columbia 2040, No CWRs"
ED_used_table$scenario[ED_used_table$scenario == "F"] <- "Columbia Restored, No CWRs"
ED_used_table$scenario[ED_used_table$scenario == "G"] <- "Columbia Current, No CWRs"

# create table with pretty format
kable(ED_used_table, col.names=c( "Scenario", "Minimum", "25% quantile","Median", "75% quantile", "Maximum"),row.names=FALSE, caption="Table 1. Percent energy used across different HexSim thermalscapes summarized for Grande Ronde River Summer Steelhead.", digits=1)
```


```{r import hourly}
# import in combined replicate DFs
A14<-fread("D:/Results_4Populations/gr_Columbia2040_current/combined/A14.csv", header=TRUE, sep=",")
B14<-fread("D:/Results_4Populations/gr_Columbiarestored_CWRcurrent/combined/B14.csv", header=TRUE, sep=",")
C14<-fread("D:/Results_4Populations/gr_current_current/combined/C14.csv", header=TRUE, sep=",")
D14<-fread("D:/Results_4Populations/gr_current_restoredCWR/combined/D14.csv", header=TRUE, sep=",")
E14<-fread("D:/Results_4Populations/gr_Columbia2040_No_CWR/combined/E14.csv", header=TRUE, sep=",")
F14<-fread("D:/Results_4Populations/gr_Columbiarestored_No_CWR/combined/F14.csv", header=TRUE, sep=",")
G14<-fread("D:/Results_4Populations/gr_current_current_No_CWR/combined/G14.csv", header=TRUE, sep=",")

# rename columns
names(A14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(B14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(C14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(D14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(E14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(F14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(G14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")

```


```{r calc DD GT 18 for each scenario}
# function to calculate cumulative degree days above a certain degree
dum_dd<-function(threshold, DF){
  DF_subset<-DF[which(DF$temp_1 >threshold),]
  dd_threshold<-aggregate(temp_1~ID, data=DF_subset, sum)
  dd_threshold$temp_1<-dd_threshold$temp_1/24
  return(dd_threshold)
}

# set threshold
thres<-18
# run for each scenario's hourly DF
A14_ddGT18<-dum_dd(thres, A14)
B14_ddGT18<-dum_dd(thres, B14)
C14_ddGT18<-dum_dd(thres, C14)
D14_ddGT18<-dum_dd(thres, D14)
E14_ddGT18<-dum_dd(thres, E14)
F14_ddGT18<-dum_dd(thres, F14)
G14_ddGT18<-dum_dd(thres, G14)
# add scenario column
A14_ddGT18$scenario<-"A"
B14_ddGT18$scenario<-"B"
C14_ddGT18$scenario<-"C"
D14_ddGT18$scenario<-"D"
E14_ddGT18$scenario<-"E"
F14_ddGT18$scenario<-"F"
G14_ddGT18$scenario<-"G"

#combine
all_14_ddGT18<-rbind.data.frame(A14_ddGT18, B14_ddGT18, C14_ddGT18, D14_ddGT18, E14_ddGT18, F14_ddGT18,G14_ddGT18)

```


```{r A14 hist}
a2<-ggplot(A14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia 2040, \nCWR Current") 
```

```{r B14 hist}
b2<-ggplot(B14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia Restored, \nCWR Current")
```

```{r C14 hist}
c2<-ggplot(C14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia Current, \nCWR Current")
```

```{r D14 hist}
d2<-ggplot(D14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia Current, \nCWR Restored")
```

```{r E14 hist}
e2<-ggplot(E14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia 2040, \nNo CWRs")
```

```{r F14 hist}
f2<-ggplot(F14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia Restored, \nNo CWRs")
```

```{r G14 hist}
g2<-ggplot(G14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1000) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia Current, \nNo CWRs")
```

```{r plot DD hist together, fig.cap="Fig. 3. Histograms of modeled Grande Ronde River summer steelhead accumulated degrees day over 18°C from Bonneville to the Snake River confluence in the Columbia River."}
plot_grid(c2, a2, b2, d2, g2, e2, f2,
          labels = c("A", "B", "C", "D", "E", "F", "G"),
          ncol = 3, nrow = 3)
```

```{r cum DD boxplot, fig.cap="Fig. 4. Boxplots of modeled Grande Ronde River summer steelhead accumulated degrees day over 18°C from Bonneville to the Snake River confluence in the Columbia River."}
all_14_ddGT18$scenario<-as.factor(all_14_ddGT18$scenario)

out3<-ggplot(all_14_ddGT18, aes(x=scenario, y=temp_1, group=scenario)) +   
  geom_boxplot() + 
  labs( y="Cumulative degree days (>18°C)", title="Grande Ronde River Summer Steelhead") + 
  theme_classic() 

out3 + theme(axis.text.x=element_text(color = "black", size=11, angle=30, vjust=.8, hjust=0.8), axis.title.x=element_blank(),) + scale_x_discrete(limits=c("C","G", "A","E", "B", "F","D"), labels=c(
  "Columbia Current,\n CWR Current",
  "Columbia Current, \nNo CWRs", 
  "Columbia 2040, \nCWR Current", 
  "Columbia 2040, \nNo CWRs", 
 "Columbia Restored, \nCWR Current", 
 "Columbia Restored, \nNo CWRs",
  "Columbia Current, \nCWR Restored")) 
```

```{r DD lost table}
DD_used_table<-aggregate(temp_1~scenario, data=all_14_ddGT18, quantile)
DD_used_table$scenario<-as.character(DD_used_table$scenario)
DD_used_table<-format(DD_used_table, digits = 0) # round 

DD_used_table$scenario[DD_used_table$scenario == "A"] <- "Columbia 2040, CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "B"] <- "Columbia Restored, CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "C"] <- "Columbia Current, CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "D"] <- "Columbia Current, CWR Restored"
DD_used_table$scenario[DD_used_table$scenario == "E"] <- "Columbia 2040, No CWRs"
DD_used_table$scenario[DD_used_table$scenario == "F"] <- "Columbia Restored, No CWRs"
DD_used_table$scenario[DD_used_table$scenario == "G"] <- "Columbia Current, No CWRs"
# create table with pretty format
kable(DD_used_table, col.names=c( "Scenario", "Minimum", "25% quantile","Median", "75% quantile", "Maximum"),row.names=FALSE, caption="Table 2. Cumulative degree days (>18°C) used across different HexSim thermalscapes summarized for Grande Ronde River Summer Steelhead.", digits=1)
```

```{r import refuges data, eval=TRUE, echo=FALSE}
# import refuges population census table
# only has refuge density for hours when a refuge is occupied
# import in combined replicate DFs
A9<-read.table("D:/Results_4Populations/gr_Columbia2040_current/combined/A9.csv", header=TRUE, sep=",")
B9<-read.table("D:/Results_4Populations/gr_Columbiarestored_CWRcurrent/combined/B9.csv", header=TRUE, sep=",")
C9<-read.table("D:/Results_4Populations/gr_current_current/combined/C9.csv", header=TRUE, sep=",")
D9<-read.table("D:/Results_4Populations/gr_current_restoredCWR/combined/D9.csv", header=TRUE, sep=",")
E9<-read.table("D:/Results_4Populations/gr_Columbia2040_No_CWR/combined/E9.csv", header=TRUE, sep=",")
F9<-read.table("D:/Results_4Populations/gr_Columbiarestored_No_CWR/combined/F9.csv", header=TRUE, sep=",")
G9<-read.table("D:/Results_4Populations/gr_current_current_No_CWR/combined/G9.csv", header=TRUE, sep=",")

# rename columns
colnames(A9)<-c("run","timestep","Population","ID", "refuge_id", "refuge_depth_chinook" ,"refuge_depth_steelhead", "effective_volume_chinook","effective_volume_steelhead", "current_refuge_density",
            "retain_chinook","retain_steelhead", "removed_chinook", "removed_steelhead")
colnames(B9)<-c("run","timestep","Population","ID", "refuge_id", "refuge_depth_chinook" ,"refuge_depth_steelhead", "effective_volume_chinook","effective_volume_steelhead", "current_refuge_density",
            "retain_chinook","retain_steelhead", "removed_chinook", "removed_steelhead")
colnames(C9)<-c("run","timestep","Population","ID", "refuge_id", "refuge_depth_chinook" ,"refuge_depth_steelhead", "effective_volume_chinook","effective_volume_steelhead", "current_refuge_density",
            "retain_chinook","retain_steelhead", "removed_chinook", "removed_steelhead")
colnames(D9)<-c("run","timestep","Population","ID", "refuge_id", "refuge_depth_chinook" ,"refuge_depth_steelhead", "effective_volume_chinook","effective_volume_steelhead", "current_refuge_density",
            "retain_chinook","retain_steelhead", "removed_chinook", "removed_steelhead")
colnames(E9)<-c("run","timestep","Population","ID", "refuge_id", "refuge_depth_chinook" ,"refuge_depth_steelhead", "effective_volume_chinook","effective_volume_steelhead", "current_refuge_density",
            "retain_chinook","retain_steelhead", "removed_chinook", "removed_steelhead")
colnames(F9)<-c("run","timestep","Population","ID", "refuge_id", "refuge_depth_chinook" ,"refuge_depth_steelhead", "effective_volume_chinook","effective_volume_steelhead", "current_refuge_density",
            "retain_chinook","retain_steelhead", "removed_chinook", "removed_steelhead")
colnames(G9)<-c("run","timestep","Population","ID", "refuge_id", "refuge_depth_chinook" ,"refuge_depth_steelhead", "effective_volume_chinook","effective_volume_steelhead", "current_refuge_density",
            "retain_chinook","retain_steelhead", "removed_chinook", "removed_steelhead")

# create dataframe to link hexsim refuge id with name of refuge
# HexSim Refuge ID in this file:
# 14 - Eagle Creek
# 15 - Rock Creek
# 16 - Herman Creek
# 17 - Wind River
# 18 - Little White Salmon River
# 19 - White Salmon River
# 20 - Klickitat River
# 21 - Deschutes River
# 22 - Umatilla River
# create sequence of refuge IDs
refuge_IDseq<-seq(14,22,1)
# create translator sequence because model adds 1 
#refuge_IDseq2<-seq(1,7,1)

# create vector of refuge names
refuge_name<-c("Eagle Creek", "Rock Creek", "Herman Creek", "Wind River", "Little White Salmon River","White Salmon River", "Klickitat River", "Deschutes River", "Umatilla River")
refuge_id<-cbind.data.frame(refuge_IDseq, refuge_name) # create dataframe to link refuge ID value with refuge Name
# merge name with refuge data
A9_2<-merge(A9, refuge_id, by.x="refuge_id", by.y="refuge_IDseq")
B9_2<-merge(B9, refuge_id, by.x="refuge_id", by.y="refuge_IDseq")
C9_2<-merge(C9, refuge_id, by.x="refuge_id", by.y="refuge_IDseq")
D9_2<-merge(D9, refuge_id, by.x="refuge_id", by.y="refuge_IDseq")
E9_2<-merge(E9, refuge_id, by.x="refuge_id", by.y="refuge_IDseq")
F9_2<-merge(F9, refuge_id, by.x="refuge_id", by.y="refuge_IDseq")
G9_2<-merge(G9, refuge_id, by.x="refuge_id", by.y="refuge_IDseq")
C_sum<-sum(C9_2$retain_steelhead)
G_sum<-sum(G9_2$retain_steelhead)
A_sum<-sum(A9_2$retain_steelhead)
E_sum<-sum(E9_2$retain_steelhead)
B_sum<-sum(B9_2$retain_steelhead)
F_sum<-sum(F9_2$retain_steelhead)
D_sum<-sum(D9_2$retain_steelhead)
sum_v<-c(C_sum, G_sum, A_sum, E_sum,B_sum, F_sum, D_sum )

names_v<-c("Columbia Current,CWR Current",
  "Columbia Current, No CWRs", 
  "Columbia 2040, Current", 
  "Columbia 2040, No CWRs", 
 "Columbia Restored, Current", 
 "Columbia Restored, No CWRs",
  "Columbia Current, Restored")
refuge_use_all<-cbind(names_v, sum_v)
kable(refuge_use_all, col.names=c("Scenario", "Total CWR Residence (h)"), caption="Table 3. Model output for total hours residing n cold water refuges summarized for Grande Ronde River Summer Steelhead.")
```

```{r summarize dying fish}
# import in combined replicate DFs
A12<-read.table("D:/Results_4Populations/gr_Columbia2040_current/combined/A12.csv", header=TRUE, sep=",")
B12<-read.table("D:/Results_4Populations/gr_Columbiarestored_CWRcurrent/combined/B12.csv", header=TRUE, sep=",")
C12<-read.table("D:/Results_4Populations/gr_current_current/combined/C12.csv", header=TRUE, sep=",")
D12<-read.table("D:/Results_4Populations/gr_current_restoredCWR/combined/D12.csv", header=TRUE, sep=",")
E12<-read.table("D:/Results_4Populations/gr_Columbia2040_No_CWR/combined/E12.csv", header=TRUE, sep=",")
F12<-read.table("D:/Results_4Populations/gr_Columbiarestored_No_CWR/combined/F12.csv", header=TRUE, sep=",")
G12<-read.table("D:/Results_4Populations/gr_current_current_No_CWR/combined/G12.csv", header=TRUE, sep=",")

# get number of individuals died from acute temperature stress
acute_A<-((dim(A12)[1])/ 2000) * 100
acute_B<-((dim(B12)[1])/ 2000) * 100
acute_C<-((dim(C12)[1])/ 2000) * 100
acute_D<-((dim(D12)[1])/ 2000) * 100
acute_E<-((dim(E12)[1])/ 2000) * 100
acute_F<-((dim(F12)[1])/ 2000) * 100
acute_G<-((dim(G12)[1])/ 2000) * 100
acute_v<-c(acute_C, acute_G, acute_A, acute_E,acute_B, acute_F, acute_D)
acute_all<-cbind(names_v, acute_v)
kable(acute_all, col.names=c("Scenario", "Total mortality"), caption="Table 4. Model output for percent of individuals dying from acute temperature stress summarized for Grande Ronde River Summer Steelhead.")

```



```{r time in system histogram}
all_13$Time_in_system_d<-all_13$Time_in_system / 24
all_13_labels<-all_13
# vector of scenario labels
all_13_labels$scenario<-as.factor(all_13_labels$scenario)
levels(all_13_labels$scenario)[levels(all_13_labels$scenario)=="A"] <-"Columbia 2040, CWR Current"
levels(all_13_labels$scenario)[levels(all_13_labels$scenario)=="B"] <-"Columbia Restored, CWR Current"
levels(all_13_labels$scenario)[levels(all_13_labels$scenario)=="C"] <-"Columbia Current, CWR Current"
levels(all_13_labels$scenario)[levels(all_13_labels$scenario)=="D"] <-"Columbia Current, CWR Restored"
levels(all_13_labels$scenario)[levels(all_13_labels$scenario)=="E"] <-"Columbia 2040, No CWRs"
levels(all_13_labels$scenario)[levels(all_13_labels$scenario)=="F"] <-"Columbia Restored, No CWRs"
levels(all_13_labels$scenario)[levels(all_13_labels$scenario)=="G"] <-"Columbia Current, No CWRs"

#v_names<-c("Columbia 2040- CWR Current", "Columbia Restored- CWR Current","Columbia Current- CWR Current", "Columbia #Current- CWR Restored", "Columbia 2040- No CWRs", "Columbia Restored- No CWRs","Columbia Current- No CWRs" )
p <- ggplot(data = all_13_labels, aes(x = Time_in_system_d)) + geom_histogram(binwidth = 10) 
p + facet_wrap(~scenario) + labs(x="Passage time (d)", y="Count", title="Grande Ronde River Summer Steelhead") 
```


```{r terminus arrival histogram}
# model starts on July 1 which is equivalent to julian day 182
jday_start<-182
# step is hour got to terminus
# convert Step to julian day
all_13_labels$jday<-floor(all_13_labels$Step / 24) + jday_start
# convert julian day to date
all_13_labels$date_ch<-chron(all_13_labels$jday, origin=c(month=1, day=1, year=2019))
# convert date format to posixct
all_13_labels$date<- as.POSIXct(all_13_labels$date_ch, "GMT") 

# histograms
p <- ggplot(data = all_13_labels, aes(x = date)) + geom_histogram()
p + facet_wrap(~scenario) + labs(x="Exit Day", y="Count", title="Grande Ronde River Summer Steelhead")
```


```{r terminus arrival histogram observed}
psg_timing_gr_keefer <- read_csv("D:/HexSim_Models/CWR_Columbia/Calibration/MKeefer_data/psg_timing_gr_keefer.csv", 
col_types = cols(bodate = col_date(format = "%m/%d/%Y"), 
grdate = col_date(format = "%m/%d/%Y"), 
ihdate = col_date(format = "%m/%d/%Y"), 
mndate = col_date(format = "%m/%d/%Y")))
names(psg_timing_gr_keefer)<-c("Year", "bodate", "BO_jul", "mndate", "ihdate", "ih_jul", "grdate", "bo_mn_d", "bo_ih_d", "ih_gr_d")
d <- ggplot(data = psg_timing_gr_keefer, aes(x = bo_mn_d)) + geom_histogram() + xlim(0,260) + labs(x="Observed Passage time (days from Bonneville to McNary)")
```


```{r plot of passage days for current current scenario}
columbia_current_cwr_current<-dplyr::filter(all_13_labels, scenario == "Columbia Current, CWR Current")
e<-ggplot(data=columbia_current_cwr_current, aes(x=Time_in_system_d)) + geom_histogram() + xlim(0,260) + labs(x="Modeled Passage time (days from Bonneville to Snake River confluence)")
```


```{r plot of passage days for current scenario with keefer observed data, fig.cap="Fig. 7. Histograms of modeled Grande Ronde River summer steelhead passage days from Bonneville to the Snake River confluence in the Columbia River and observed passage days from Bonneville to McNary summarized from pit tag data (Keefer)."}
plot_grid(d,e,
          labels = c("A", "B"),
          ncol = 1, nrow = 2)
```

```{r plot of mcnary passage date observed}
# create julian date for mcnary
psg_timing_gr_keefer$mc_jul<-psg_timing_gr_keefer$BO_jul + psg_timing_gr_keefer$bo_mn_d

# convert julian day to date
psg_timing_gr_keefer$mc_date_ch<-chron(psg_timing_gr_keefer$mc_jul, origin=c(month=1, day=1, year=2019))
# convert date format to posixct
psg_timing_gr_keefer$mc_date_4_plot<- as.POSIXct(psg_timing_gr_keefer$mc_date_ch, "GMT") 

f <- ggplot(data = psg_timing_gr_keefer, aes(x = mc_date_4_plot)) + geom_histogram()  + labs(x="Observed Passage date (McNary Dam)")
f
```


```{r}
g<-ggplot(data=columbia_current_cwr_current, aes(x=date)) + geom_histogram()  +labs(x="Modeled Passage time (days from Bonneville to Snake River confluence)")
g
```

```{r}

```

