---
title: "Grande Ronde summer steelhead cumulative DD"
author: "MNSnyder"
date: "9/4/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

Grande Ronde summer steelhead Columbia River temperature time series from 2017. 
4 scenarios included:

* Columbia River 2017
* Columbia River 2017, no CWRs
* Columbia River 2017 plus 1
* Columbia River 2017 plus 1, no CWRs

Columbia 2017B assigns the John Day Pool temperature from the John Day forebay, which is the warmer part of the pool.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
library(ggplot2)
library(cowplot)
library(data.table)
library(knitr)
library(chron)
```


```{r plot formatting}
width1 = 4.5
height1 = 3.5
text1 = 8

My_Theme_CDF = theme(
  axis.title.x = element_text(size = 16),
  axis.text.x = element_text(size = 16),
  axis.title.y = element_text(size = 16),   
  axis.text.y = element_text(size = 16),
  plot.margin = margin(6, 0, 6, 0)
)
```

```{r import hourly}
# import in combined replicate DFs
A14<-fread("D:/Results_4Populations/gr_Columbia2017B/combined/E14.csv", header=TRUE, sep=",")
B14<-fread("D:/Results_4Populations/gr_Columbia2017B_NoCWR/combined/F14.csv", header=TRUE, sep=",")
C14<-fread("D:/Results_4Populations/gr_Columbia2017BplusOne/combined/G14.csv", header=TRUE, sep=",")
D14<-fread("D:/Results_4Populations/gr_Columbia2017BplusOne_NoCWR/combined/H14.csv", header=TRUE, sep=",")

# rename columns
names(A14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(B14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(C14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(D14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")

```

## DD > 18 °C
```{r calc DD GT 18 for each scenario}
# function to calculate cumulative degree days above a certain degree
dum_dd<-function(threshold, DF){
  DF_subset<-DF[which(DF$temp_1 >= threshold),]
  dd_threshold<-aggregate(temp_1~ID, data=DF_subset, sum)
  dd_threshold$temp_1<-dd_threshold$temp_1/24
  return(dd_threshold)
}

# set threshold
thres<-18
# run for each scenario's hourly DF
A14_ddGT18<-dum_dd(thres, A14)
B14_ddGT18<-dum_dd(thres, B14)
C14_ddGT18<-dum_dd(thres, C14)
D14_ddGT18<-dum_dd(thres, D14)

# add scenario column
A14_ddGT18$scenario<-"A"
B14_ddGT18$scenario<-"B"
C14_ddGT18$scenario<-"C"
D14_ddGT18$scenario<-"D"

#combine
all_14_ddGT18<-rbind.data.frame(A14_ddGT18, B14_ddGT18, C14_ddGT18, D14_ddGT18)

```


```{r A14 hist}
a2<-ggplot(A14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1400) + ylim(0,35) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia 2017, \nCWR Current") 
```

```{r B14 hist}
b2<-ggplot(B14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1400) + ylim(0,35) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia 2017, \nNo CWR")
```

```{r C14 hist}
c2<-ggplot(C14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1400) + ylim(0,35) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia 2040 (2017), \nCWR Current")
```

```{r D14 hist}
d2<-ggplot(D14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1400) + ylim(0,35) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia 2040 (2017), \nNo CWR")
```

```{r plot DD hist together, fig.cap="Fig. 1. Histograms of modeled Grande Ronde River summer steelhead accumulated degrees day over 18°C from Bonneville to the Snake River confluence in the Columbia River."}
plot_grid(a2, b2, c2, d2,
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2)
```

```{r cum DD boxplot, fig.cap="Fig. 2. Boxplots of modeled Grande Ronde River summer steelhead accumulated degrees day over 18°C from Bonneville to the Snake River confluence in the Columbia River."}
all_14_ddGT18$scenario<-as.factor(all_14_ddGT18$scenario)

out3<-ggplot(all_14_ddGT18, aes(x=scenario, y=temp_1, group=scenario)) +   
  geom_boxplot() + 
  labs( y="Cumulative degree days (>18°C)", title="Grande Ronde River Summer Steelhead") + 
  theme_classic() 

out3 + theme(axis.text.x=element_text(color = "black", size=11, angle=30, vjust=.8, hjust=0.8), axis.title.x=element_blank(),) + scale_x_discrete(limits=c( "A", "B","C","D"), labels=c(
  "Columbia 2017,\n CWR Current",
  "Columbia 2017, \nNo CWRs", 
  "Columbia 2040 (2017), \nCWR Current", 
  "Columbia 2040 (2017), \nNo CWRs")) 
```

```{r DD lost table}
DD_used_table<-aggregate(temp_1~scenario, data=all_14_ddGT18, quantile)
DD_used_table$scenario<-as.character(DD_used_table$scenario)
DD_used_table<-format(DD_used_table, digits = 0) # round 

DD_used_table$scenario[DD_used_table$scenario == "A"] <- "Columbia 2017, CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "B"] <- "Columbia 2017, No CWR"
DD_used_table$scenario[DD_used_table$scenario == "C"] <- "Columbia 2040 (2017), CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "D"] <- "Columbia 2040 (2017), No CWR"

# create table with pretty format
kable(DD_used_table, col.names=c( "Scenario", "Minimum", "25% quantile","Median", "75% quantile", "Maximum"),row.names=FALSE, caption="Table 1. Cumulative degree days (>18°C) used across different HexSim thermalscapes summarized for Grande Ronde River Summer Steelhead.", digits=1)
```

###################################################################
## Degree Days > 20°C

```{r calc DD GT 20 for each scenario}
# function to calculate cumulative degree days above a certain degree
dum_dd<-function(threshold, DF){
  DF_subset<-DF[which(DF$temp_1 >= threshold),]
  dd_threshold<-aggregate(temp_1~ID, data=DF_subset, sum)
  dd_threshold$temp_1<-dd_threshold$temp_1/24
  return(dd_threshold)
}

# set threshold
thres<-20
# run for each scenario's hourly DF
A14_ddGT18<-dum_dd(thres, A14)
B14_ddGT18<-dum_dd(thres, B14)
C14_ddGT18<-dum_dd(thres, C14)
D14_ddGT18<-dum_dd(thres, D14)

# add scenario column
A14_ddGT18$scenario<-"A"
B14_ddGT18$scenario<-"B"
C14_ddGT18$scenario<-"C"
D14_ddGT18$scenario<-"D"

#combine
all_14_ddGT18<-rbind.data.frame(A14_ddGT18, B14_ddGT18, C14_ddGT18, D14_ddGT18)

```


```{r A14 GT 20 hist}
a2<-ggplot(A14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1400) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>20°C)", y="Percent", title="Columbia 2017, \nCWR Current") 
```

```{r B14 GT 20 hist}
b2<-ggplot(B14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1400) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>20°C)", y="Percent", title="Columbia 2017, \nNo CWR")
```

```{r C14 GT 20 hist}
c2<-ggplot(C14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1400) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>20°C)", y="Percent", title="Columbia 2040 (2017), \nCWR Current")
```

```{r D14 GT 20 hist}
d2<-ggplot(D14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1400) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>20°C)", y="Percent", title="Columbia 2040 (2017), \nNo CWR")
```

```{r plot DD hist together GT 20, fig.cap="Fig. 1. Histograms of modeled Grande Ronde River summer steelhead accumulated degrees day over 18°C from Bonneville to the Snake River confluence in the Columbia River."}
plot_grid(a2, b2, c2, d2,
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2)
```

```{r cum DD boxplot GT 20, fig.cap="Fig. 2. Boxplots of modeled Grande Ronde River summer steelhead accumulated degrees day over 18°C from Bonneville to the Snake River confluence in the Columbia River."}
all_14_ddGT18$scenario<-as.factor(all_14_ddGT18$scenario)

out3<-ggplot(all_14_ddGT18, aes(x=scenario, y=temp_1, group=scenario)) +   
  geom_boxplot() + 
  labs( y="Cumulative degree days (>20°C)", title="Grande Ronde River Summer Steelhead") + 
  theme_classic() 

out3 + theme(axis.text.x=element_text(color = "black", size=11, angle=30, vjust=.8, hjust=0.8), axis.title.x=element_blank(),) + scale_x_discrete(limits=c( "A", "B","C","D"), labels=c(
  "Columbia 2017,\n CWR Current",
  "Columbia 2017, \nNo CWRs", 
  "Columbia 2040 (2017), \nCWR Current", 
  "Columbia 2040 (2017), \nNo CWRs")) 
```

```{r DD lost table GT 20}
DD_used_table<-aggregate(temp_1~scenario, data=all_14_ddGT18, quantile)
DD_used_table$scenario<-as.character(DD_used_table$scenario)
DD_used_table<-format(DD_used_table, digits = 0) # round 

DD_used_table$scenario[DD_used_table$scenario == "A"] <- "Columbia 2017, CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "B"] <- "Columbia 2017, No CWR"
DD_used_table$scenario[DD_used_table$scenario == "C"] <- "Columbia 2040 (2017), CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "D"] <- "Columbia 2040 (2017), No CWR"

# create table with pretty format
kable(DD_used_table, col.names=c( "Scenario", "Minimum", "25% quantile","Median", "75% quantile", "Maximum"),row.names=FALSE, caption="Table 1. Cumulative degree days (>20°C) used across different HexSim thermalscapes summarized for Grande Ronde River Summer Steelhead.", digits=1)
```

```{r prepare for DD table based on threshold 20}
# set threshold based on 75% quantile
thres<-362

a<-dim(dplyr::filter(all_14_ddGT18, temp_1 > thres & scenario =="A"))[1] / dim(dplyr::filter(all_14_ddGT18, scenario =="A"))[1]
b<-dim(dplyr::filter(all_14_ddGT18, temp_1 > thres & scenario =="B"))[1] / dim(dplyr::filter(all_14_ddGT18, scenario =="B"))[1]
c<-dim(dplyr::filter(all_14_ddGT18, temp_1 > thres & scenario =="C"))[1] / dim(dplyr::filter(all_14_ddGT18, scenario =="C"))[1]
d<-dim(dplyr::filter(all_14_ddGT18, temp_1 > thres & scenario =="D"))[1] / dim(dplyr::filter(all_14_ddGT18, scenario =="D"))[1]

out<-cbind(a*100,b*100,c*100,d*100)
# create table with pretty format
kable(out, col.names=c( "Columbia 2017, CWR Current", "Columbia 2017, No CWR", "Columbia 2040 (2017), CWR Current","Columbia 2040 (2017), No CWR"),row.names=FALSE, caption="Table 1. Percent of population with cumulative degree days (>20°C) above 135 across different HexSim thermalscapes summarized for Grande Ronde River summer steelhead.", digits=0)

```

```{r experiment with reverse CDF 20}
#ggplot(all_14_ddGT18, aes(temp_1, colour = scenario)) + stat_ecdf()

a<-dplyr::filter(all_14_ddGT18, scenario=="A")
b<-dplyr::filter(all_14_ddGT18, scenario=="B")
c<-dplyr::filter(all_14_ddGT18, scenario=="C")
d<-dplyr::filter(all_14_ddGT18, scenario=="D")

# function to get reverse of eCDF
rcdf <- function (x) {
     cdf <- ecdf(x)
     y <- cdf(x)
    xrcdf <- 1-y
}

# reverse ecdf for A
atest2<-rcdf(a$temp_1)
atest3<-cbind(atest2, a)
names(atest3)[1]<-'Percent'
# reverse ecdf for B
btest2<-rcdf(b$temp_1)
btest3<-cbind(btest2, b)
names(btest3)[1]<-'Percent'
# reverse ecdf for C
ctest2<-rcdf(c$temp_1)
ctest3<-cbind(ctest2, c)
names(ctest3)[1]<-'Percent'
# reverse ecdf for D
dtest2<-rcdf(d$temp_1)
dtest3<-cbind(dtest2, d)
names(dtest3)[1]<-'Percent'

rev_cdf_all<-rbind.data.frame(atest3, btest3, ctest3, dtest3)

# shows proportin of population that has greater than that DD accumulation
plot(atest2~temp_1, data=atest3, col="blue")
points(btest2~temp_1, data=btest3, col="red")


gr_20<-ggplot(rev_cdf_all, aes(x =temp_1, y=Percent, group=scenario )) + 
  geom_line(aes(linetype=scenario, color=scenario), size=1) +
  theme_classic()+
  labs(x="Cumulative Degree Days (>20°C)")+ xlim(0,1000)+
    scale_linetype_manual(name="", values=c("solid", "twodash", "solid", "twodash"), labels = c("Current temperature with CWRs", "Current temperature without CWRs", "Future temperature with CWRs", "Future temperature without CWRs"))+
  scale_color_manual(name="", values=c('blue3','blue3', 'firebrick3','firebrick3'), labels = c("Current temperature with CWRs", "Current temperature without CWRs", "Future temperature with CWRs", "Future temperature without CWRs")) + 
  My_Theme_CDF

```

###################################################################
## Degree Days > 21°C

```{r calc DD GT 21 for each scenario}
# function to calculate cumulative degree days above a certain degree
dum_dd<-function(threshold, DF){
  DF_subset<-DF[which(DF$temp_1 >= threshold),]
  dd_threshold<-aggregate(temp_1~ID, data=DF_subset, sum)
  dd_threshold$temp_1<-dd_threshold$temp_1/24
  return(dd_threshold)
}

# set threshold
thres<-21
# run for each scenario's hourly DF
A14_ddGT18<-dum_dd(thres, A14)
B14_ddGT18<-dum_dd(thres, B14)
C14_ddGT18<-dum_dd(thres, C14)
D14_ddGT18<-dum_dd(thres, D14)

# add scenario column
A14_ddGT18$scenario<-"A"
B14_ddGT18$scenario<-"B"
C14_ddGT18$scenario<-"C"
D14_ddGT18$scenario<-"D"

#combine
all_14_ddGT18<-rbind.data.frame(A14_ddGT18, B14_ddGT18, C14_ddGT18, D14_ddGT18)

```


```{r A14 GT 21 hist}
a2<-ggplot(A14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1400) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>21°C)", y="Percent", title="Columbia 2017, \nCWR Current") 
```

```{r B14 GT 21 hist}
b2<-ggplot(B14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1400) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>21°C)", y="Percent", title="Columbia 2017, \nNo CWR")
```

```{r C14 GT 21 hist}
c2<-ggplot(C14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1400) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>21°C)", y="Percent", title="Columbia 2040 (2017), \nCWR Current")
```

```{r D14 GT 21 hist}
d2<-ggplot(D14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1400) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>21°C)", y="Percent", title="Columbia 2040 (2017), \nNo CWR")
```

```{r plot DD hist together GT 21, fig.cap="Fig. 1. Histograms of modeled Grande Ronde River summer steelhead accumulated degrees day over 21°C from Bonneville to the Snake River confluence in the Columbia River."}
plot_grid(a2, b2, c2, d2,
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2)
```

```{r cum DD boxplot GT 21, fig.cap="Fig. 2. Boxplots of modeled Grande Ronde River summer steelhead accumulated degrees day over 21°C from Bonneville to the Snake River confluence in the Columbia River."}
all_14_ddGT18$scenario<-as.factor(all_14_ddGT18$scenario)

out3<-ggplot(all_14_ddGT18, aes(x=scenario, y=temp_1, group=scenario)) +   
  geom_boxplot() + 
  labs( y="Cumulative degree days (>21°C)", title="Grande Ronde River Summer Steelhead") + 
  theme_classic() 

out3 + theme(axis.text.x=element_text(color = "black", size=11, angle=30, vjust=.8, hjust=0.8), axis.title.x=element_blank(),) + scale_x_discrete(limits=c( "A", "B","C","D"), labels=c(
  "Columbia 2017,\n CWR Current",
  "Columbia 2017, \nNo CWRs", 
  "Columbia 2040 (2017), \nCWR Current", 
  "Columbia 2040 (2017), \nNo CWRs")) 
```

```{r DD lost table GT 21}
DD_used_table<-aggregate(temp_1~scenario, data=all_14_ddGT18, quantile)
DD_used_table$scenario<-as.character(DD_used_table$scenario)
DD_used_table<-format(DD_used_table, digits = 0) # round 

DD_used_table$scenario[DD_used_table$scenario == "A"] <- "Columbia 2017, CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "B"] <- "Columbia 2017, No CWR"
DD_used_table$scenario[DD_used_table$scenario == "C"] <- "Columbia 2040 (2017), CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "D"] <- "Columbia 2040 (2017), No CWR"

# create table with pretty format
kable(DD_used_table, col.names=c( "Scenario", "Minimum", "25% quantile","Median", "75% quantile", "Maximum"),row.names=FALSE, caption="Table 1. Cumulative degree days (>21°C) used across different HexSim thermalscapes summarized for Grande Ronde River Summer Steelhead.", digits=1)
```



```{r prepare for DD table based on threshold 21}
# set threshold based on 75% quantile
thres<-341

a<-dim(dplyr::filter(all_14_ddGT18, temp_1 > thres & scenario =="A"))[1] / dim(dplyr::filter(all_14_ddGT18, scenario =="A"))[1]
b<-dim(dplyr::filter(all_14_ddGT18, temp_1 > thres & scenario =="B"))[1] / dim(dplyr::filter(all_14_ddGT18, scenario =="B"))[1]
c<-dim(dplyr::filter(all_14_ddGT18, temp_1 > thres & scenario =="C"))[1] / dim(dplyr::filter(all_14_ddGT18, scenario =="C"))[1]
d<-dim(dplyr::filter(all_14_ddGT18, temp_1 > thres & scenario =="D"))[1] / dim(dplyr::filter(all_14_ddGT18, scenario =="D"))[1]

out<-cbind(a*100,b*100,c*100,d*100)
# create table with pretty format
kable(out, col.names=c( "Columbia 2017, CWR Current", "Columbia 2017, No CWR", "Columbia 2040 (2017), CWR Current","Columbia 2040 (2017), No CWR"),row.names=FALSE, caption="Table 1. Percent of population with cumulative degree days (>21°C) above 135 across different HexSim thermalscapes summarized for Grande Ronde River summer steelhead.", digits=0)

```

```{r reverse CDF 21}
#ggplot(all_14_ddGT18, aes(temp_1, colour = scenario)) + stat_ecdf()

a<-dplyr::filter(all_14_ddGT18, scenario=="A")
b<-dplyr::filter(all_14_ddGT18, scenario=="B")
c<-dplyr::filter(all_14_ddGT18, scenario=="C")
d<-dplyr::filter(all_14_ddGT18, scenario=="D")

# function to get reverse of eCDF
rcdf <- function (x) {
     cdf <- ecdf(x)
     y <- cdf(x)
    xrcdf <- 1-y
}

# reverse ecdf for A
atest2<-rcdf(a$temp_1)
atest3<-cbind(atest2, a)
names(atest3)[1]<-'Percent'
# reverse ecdf for B
btest2<-rcdf(b$temp_1)
btest3<-cbind(btest2, b)
names(btest3)[1]<-'Percent'
# reverse ecdf for C
ctest2<-rcdf(c$temp_1)
ctest3<-cbind(ctest2, c)
names(ctest3)[1]<-'Percent'
# reverse ecdf for D
dtest2<-rcdf(d$temp_1)
dtest3<-cbind(dtest2, d)
names(dtest3)[1]<-'Percent'

rev_cdf_all<-rbind.data.frame(atest3, btest3, ctest3, dtest3)

# shows proportin of population that has greater than that DD accumulation
plot(atest2~temp_1, data=atest3, col="blue")
points(btest2~temp_1, data=btest3, col="red")


gr_21<-ggplot(rev_cdf_all, aes(x =temp_1, y=Percent, group=scenario )) + 
  geom_line(aes(linetype=scenario, color=scenario), size=1) +
  theme_classic()+
  labs(x="Cumulative Degree Days (>21°C)")+ xlim(0,1000)+
    scale_linetype_manual(name="", values=c("solid", "twodash", "solid", "twodash"), labels = c("Current temperature with CWRs", "Current temperature without CWRs", "Future temperature with CWRs", "Future temperature without CWRs"))+
  scale_color_manual(name="", values=c('blue3','blue3', 'firebrick3','firebrick3'), labels = c("Current temperature with CWRs", "Current temperature without CWRs", "Future temperature with CWRs", "Future temperature without CWRs"))+
  My_Theme_CDF

```


###################################################################
## Degree Days > 22°C

```{r calc DD GT 22 for each scenario}
# function to calculate cumulative degree days above a certain degree
dum_dd<-function(threshold, DF){
  DF_subset<-DF[which(DF$temp_1 >= threshold),]
  dd_threshold<-aggregate(temp_1~ID, data=DF_subset, sum)
  dd_threshold$temp_1<-dd_threshold$temp_1/24
  return(dd_threshold)
}

# set threshold
thres<-22
# run for each scenario's hourly DF
A14_ddGT18<-dum_dd(thres, A14)
B14_ddGT18<-dum_dd(thres, B14)
C14_ddGT18<-dum_dd(thres, C14)
D14_ddGT18<-dum_dd(thres, D14)

# add scenario column
A14_ddGT18$scenario<-"A"
B14_ddGT18$scenario<-"B"
C14_ddGT18$scenario<-"C"
D14_ddGT18$scenario<-"D"

#combine
all_14_ddGT18<-rbind.data.frame(A14_ddGT18, B14_ddGT18, C14_ddGT18, D14_ddGT18)

```


```{r A14 GT 22 hist}
a2<-ggplot(A14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1400) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>22°C)", y="Percent", title="Columbia 2017, \nCWR Current") 
```

```{r B14 GT 22 hist}
b2<-ggplot(B14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1400) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>22°C)", y="Percent", title="Columbia 2017, \nNo CWR")
```

```{r C14 GT 22 hist}
c2<-ggplot(C14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1400) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>22°C)", y="Percent", title="Columbia 2040 (2017), \nCWR Current")
```

```{r D14 GT 22 hist}
d2<-ggplot(D14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1400) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>22°C)", y="Percent", title="Columbia 2040 (2017), \nNo CWR")
```

```{r plot DD hist together GT 22, fig.cap="Fig. 1. Histograms of modeled Grande Ronde River summer steelhead accumulated degrees day over 22°C from Bonneville to the Snake River confluence in the Columbia River."}
plot_grid(a2, b2, c2, d2,
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2)
```

```{r cum DD boxplot GT 22, fig.cap="Fig. 2. Boxplots of modeled Grande Ronde River summer steelhead accumulated degrees day over 22°C from Bonneville to the Snake River confluence in the Columbia River."}
all_14_ddGT18$scenario<-as.factor(all_14_ddGT18$scenario)

out3<-ggplot(all_14_ddGT18, aes(x=scenario, y=temp_1, group=scenario)) +   
  geom_boxplot() + ylim(0,800) +
   labs( y="Cumulative degree days (>22°C)", title="Grande Ronde River Summer Steelhead") + 
  theme_classic() 

out3 + theme(axis.text.x=element_text(color = "black", size=11, angle=30, vjust=.8, hjust=0.8), axis.title.x=element_blank(),) + scale_x_discrete(limits=c( "A", "B","C","D"), labels=c(
  "Columbia 2017,\n CWR Current",
  "Columbia 2017, \nNo CWRs", 
  "Columbia 2040 (2017), \nCWR Current", 
  "Columbia 2040 (2017), \nNo CWRs")) 
```

```{r DD lost table GT 22}
DD_used_table<-aggregate(temp_1~scenario, data=all_14_ddGT18, quantile)
DD_used_table$scenario<-as.character(DD_used_table$scenario)
DD_used_table<-format(DD_used_table, digits = 0) # round 

DD_used_table$scenario[DD_used_table$scenario == "A"] <- "Columbia 2017, CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "B"] <- "Columbia 2017, No CWR"
DD_used_table$scenario[DD_used_table$scenario == "C"] <- "Columbia 2040 (2017), CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "D"] <- "Columbia 2040 (2017), No CWR"

# create table with pretty format
kable(DD_used_table, col.names=c( "Scenario", "Minimum", "25% quantile","Median", "75% quantile", "Maximum"),row.names=FALSE, caption="Table 1. Cumulative degree days (>22°C) used across different HexSim thermalscapes summarized for Grande Ronde River Summer Steelhead.", digits=1)
```


```{r prepare for DD table based on threshold 22}
# set threshold based on 75% quantile
thres<-252

a<-dim(dplyr::filter(all_14_ddGT18, temp_1 > thres & scenario =="A"))[1] / dim(dplyr::filter(all_14_ddGT18, scenario =="A"))[1]
b<-dim(dplyr::filter(all_14_ddGT18, temp_1 > thres & scenario =="B"))[1] / dim(dplyr::filter(all_14_ddGT18, scenario =="B"))[1]
c<-dim(dplyr::filter(all_14_ddGT18, temp_1 > thres & scenario =="C"))[1] / dim(dplyr::filter(all_14_ddGT18, scenario =="C"))[1]
d<-dim(dplyr::filter(all_14_ddGT18, temp_1 > thres & scenario =="D"))[1] / dim(dplyr::filter(all_14_ddGT18, scenario =="D"))[1]

out<-cbind(a*100,b*100,c*100,d*100)
# create table with pretty format
kable(out, col.names=c( "Columbia 2017, CWR Current", "Columbia 2017, No CWR", "Columbia 2040 (2017), CWR Current","Columbia 2040 (2017), No CWR"),row.names=FALSE, caption="Table 1. Percent of population with cumulative degree days (>22°C) above 135 across different HexSim thermalscapes summarized for Grande Ronde River summer steelhead.", digits=0)

```


```{r experiment with reverse CDF}
#ggplot(all_14_ddGT18, aes(temp_1, colour = scenario)) + stat_ecdf()

a<-dplyr::filter(all_14_ddGT18, scenario=="A")
b<-dplyr::filter(all_14_ddGT18, scenario=="B")
c<-dplyr::filter(all_14_ddGT18, scenario=="C")
d<-dplyr::filter(all_14_ddGT18, scenario=="D")

# function to get reverse of eCDF
rcdf <- function (x) {
     cdf <- ecdf(x)
     y <- cdf(x)
    xrcdf <- 1-y
}

# reverse ecdf for A
atest2<-rcdf(a$temp_1)
atest3<-cbind(atest2, a)
names(atest3)[1]<-'Percent'
# reverse ecdf for B
btest2<-rcdf(b$temp_1)
btest3<-cbind(btest2, b)
names(btest3)[1]<-'Percent'
# reverse ecdf for C
ctest2<-rcdf(c$temp_1)
ctest3<-cbind(ctest2, c)
names(ctest3)[1]<-'Percent'
# reverse ecdf for D
dtest2<-rcdf(d$temp_1)
dtest3<-cbind(dtest2, d)
names(dtest3)[1]<-'Percent'

rev_cdf_all<-rbind.data.frame(atest3, btest3, ctest3, dtest3)

# shows proportin of population that has greater than that DD accumulation
plot(atest2~temp_1, data=atest3, col="blue")
points(btest2~temp_1, data=btest3, col="red")


gr_22<-ggplot(rev_cdf_all, aes(x =temp_1, y=Percent, group=scenario )) + 
  geom_line(aes(linetype=scenario, color=scenario), size=1) +
  theme_classic()+
  labs(x="Cumulative Degree Days (>22°C)")+ xlim(0,1000)+
    scale_linetype_manual(name="", values=c("solid", "twodash", "solid", "twodash"), labels = c("Current temperature with CWRs", "Current temperature without CWRs", "Future temperature with CWRs", "Future temperature without CWRs"))+
  scale_color_manual(name="", values=c('blue3','blue3', 'firebrick3','firebrick3'), labels = c("Current temperature with CWRs", "Current temperature without CWRs", "Future temperature with CWRs", "Future temperature without CWRs"))+  My_Theme_CDF

```


```{r plot reverse CDF together, fig.cap="Fig. X. Percent of population at any cumulative degree threshold that has greater cumulative exposure thant than the threshold."}

pg1<- plot_grid(
  gr_20 + theme(legend.position="none"),
  gr_21+ theme(legend.position="none"),
  gr_22 + theme(legend.position="none"),
  labels = c("A", "B", "C"),
  nrow = 3
)

# extract a legend that is laid out horizontally
legend_b <- get_legend(
  gr_20 + guides(color = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom")
)

# add the legend underneath the row we made earlier. Give it 10%
# of the height of one plot (via rel_heights).
plot_grid(pg1, legend_b, nrow = 2, rel_heights = c(1, .1))
#plot_grid(gr_20, gr_21, gr_22,
#          labels = c("A", "B", "C"),
#          ncol = 1, nrow = 3)
```


###################################################################
## Degree Days > 23°C

```{r calc DD GT 23 for each scenario}
# function to calculate cumulative degree days above a certain degree
dum_dd<-function(threshold, DF){
  DF_subset<-DF[which(DF$temp_1 >= threshold),]
  dd_threshold<-aggregate(temp_1~ID, data=DF_subset, sum)
  dd_threshold$temp_1<-dd_threshold$temp_1/24
  return(dd_threshold)
}

# set threshold
thres<-23
# run for each scenario's hourly DF
A14_ddGT18<-dum_dd(thres, A14)
B14_ddGT18<-dum_dd(thres, B14)
C14_ddGT18<-dum_dd(thres, C14)
D14_ddGT18<-dum_dd(thres, D14)

# add scenario column
A14_ddGT18$scenario<-"A"
B14_ddGT18$scenario<-"B"
C14_ddGT18$scenario<-"C"
D14_ddGT18$scenario<-"D"

#combine
all_14_ddGT18<-rbind.data.frame(A14_ddGT18, B14_ddGT18, C14_ddGT18, D14_ddGT18)

```


```{r A14 GT 23 hist}
a2<-ggplot(A14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1400) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>23°C)", y="Percent", title="Columbia 2017, \nCWR Current") 
```

```{r B14 GT 23 hist}
b2<-ggplot(B14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1400) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>23°C)", y="Percent", title="Columbia 2017, \nNo CWR")
```

```{r C14 GT 23 hist}
c2<-ggplot(C14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1400) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>23°C)", y="Percent", title="Columbia 2040 (2017), \nCWR Current")
```

```{r D14 GT 23 hist}
d2<-ggplot(D14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,1400) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>23°C)", y="Percent", title="Columbia 2040 (2017), \nNo CWR")
```

```{r plot DD hist together GT 23, fig.cap="Fig. 1. Histograms of modeled Grande Ronde River summer steelhead accumulated degrees day over 23°C from Bonneville to the Snake River confluence in the Columbia River."}
plot_grid(a2, b2, c2, d2,
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2)
```

```{r cum DD boxplot GT 23, fig.cap="Fig. 2. Boxplots of modeled Grande Ronde River summer steelhead accumulated degrees day over 23°C from Bonneville to the Snake River confluence in the Columbia River."}
all_14_ddGT18$scenario<-as.factor(all_14_ddGT18$scenario)

out3<-ggplot(all_14_ddGT18, aes(x=scenario, y=temp_1, group=scenario)) +   
  geom_boxplot() + ylim(0,800) +
   labs( y="Cumulative degree days (>23°C)", title="Grande Ronde River Summer Steelhead") + 
  theme_classic() 

out3 + theme(axis.text.x=element_text(color = "black", size=11, angle=30, vjust=.8, hjust=0.8), axis.title.x=element_blank(),) + scale_x_discrete(limits=c( "A", "B","C","D"), labels=c(
  "Columbia 2017,\n CWR Current",
  "Columbia 2017, \nNo CWRs", 
  "Columbia 2040 (2017), \nCWR Current", 
  "Columbia 2040 (2017), \nNo CWRs")) 
```

```{r DD lost table GT 23}
DD_used_table<-aggregate(temp_1~scenario, data=all_14_ddGT18, quantile)
DD_used_table$scenario<-as.character(DD_used_table$scenario)
DD_used_table<-format(DD_used_table, digits = 0) # round 

DD_used_table$scenario[DD_used_table$scenario == "A"] <- "Columbia 2017, CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "B"] <- "Columbia 2017, No CWR"
DD_used_table$scenario[DD_used_table$scenario == "C"] <- "Columbia 2040 (2017), CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "D"] <- "Columbia 2040 (2017), No CWR"

# create table with pretty format
kable(DD_used_table, col.names=c( "Scenario", "Minimum", "25% quantile","Median", "75% quantile", "Maximum"),row.names=FALSE, caption="Table 1. Cumulative degree days (>23°C) used across different HexSim thermalscapes summarized for Grande Ronde River Summer Steelhead.", digits=1)
```

