---
title: "Snake summarize fitness outcomes"
author: "MNSnyder"
date: "8/19/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
library(ggplot2)
library(cowplot)
library(data.table)
library(knitr)

```


```{r import end condition}
# import in combined replicate DFs
A13<-read.table("D:/Results_4Populations/snake_Columbia2040_current/combined/A4.csv", header=TRUE, sep=",")
B13<-read.table("D:/Results_4Populations/snake_Columbiarestored_CWRcurrent/combined/B4.csv", header=TRUE, sep=",")
C13<-read.table("D:/Results_4Populations/snake_current_current/combined/C4.csv", header=TRUE, sep=",")
D13<-read.table("D:/Results_4Populations/snake_current_restoredCWR/combined/D4.csv", header=TRUE, sep=",")
# rename DF columns
names(A13)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")
names(B13)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")
names(C13)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")
names(D13)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")

```

```{r created energy used for all scenarios}
A13$energy_density_used<-A13$Initial_energy_density-A13$Fitness_energy_density
A13$ED_per_used<-(A13$energy_density_used / A13$Initial_energy_density) * 100
A13$scenario<-"A"

B13$energy_density_used<-B13$Initial_energy_density-B13$Fitness_energy_density
B13$ED_per_used<-(B13$energy_density_used / B13$Initial_energy_density) * 100
B13$scenario<-"B"

C13$energy_density_used<-C13$Initial_energy_density-C13$Fitness_energy_density
C13$ED_per_used<-(C13$energy_density_used / C13$Initial_energy_density) * 100
C13$scenario<-"C"

D13$energy_density_used<-D13$Initial_energy_density-D13$Fitness_energy_density
D13$ED_per_used<-(D13$energy_density_used / D13$Initial_energy_density) * 100
D13$scenario<-"D"

all_13<-rbind.data.frame(A13, B13, C13, D13)
```

```{r plot formatting}
width1 = 4.5
height1 = 3.5
text1 = 14
```

```{r A13 hist}
a1<-ggplot(A13, aes(x=ED_per_used)) + geom_histogram(aes(x=ED_per_used, y=100 * (..count..)/sum(..count..))) + xlim(0,15) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        axis.title=element_text(size=text1)) + labs(x="Energy Used (%)", y="Percent", title="Columbia 2040, CWR Current") 
```

```{r B13 hist}
b1<-ggplot(B13, aes(x=ED_per_used)) + geom_histogram(aes(x=ED_per_used, y=100 * (..count..)/sum(..count..))) + xlim(0,15) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        axis.title=element_text(size=text1)) + labs(x="Energy Used (%)", y="Percent", title="Columbia Restored, CWR Current")
```

```{r C13 hist}
c1<-ggplot(C13, aes(x=ED_per_used)) + geom_histogram(aes(x=ED_per_used, y=100 * (..count..)/sum(..count..))) + xlim(0,15) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        axis.title=element_text(size=text1)) + labs(x="Energy Used (%)", y="Percent", title="Columbia Current, CWR Current")
```

```{r D13 hist}
d1<-ggplot(D13, aes(x=ED_per_used)) + geom_histogram(aes(x=ED_per_used, y=100 * (..count..)/sum(..count..))) + xlim(0,15) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        axis.title=element_text(size=text1)) + labs(x="Energy Used (%)", y="Percent", title="Columbia Current, CWR Restored")
```

```{r plot energy hist together, fig.cap="Fig. 1. Histogram of percent energy lost for modeled Snake River fall chinook salmon migrating through four different modeled thermalscapes."}
plot_grid(c1, a1, b1,  d1, 
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2)
```


```{r energy lost boxplot, fig.cap="Fig. 2. Boxplot of percent energy lost for modeled Snake River fall chinook salmon migrating through four different modeled thermalscapes."}
all_13$scenario<-as.factor(all_13$scenario)

out2<-ggplot(all_13, aes(x=scenario, y=ED_per_used, group=scenario)) +   
  geom_boxplot() + 
  labs( y="Energy lost (%)", title="Snake River fall chinook salmon") + 
  theme_classic() 

out2 + theme(axis.text.x=element_text(color = "black", size=11, angle=30, vjust=.8, hjust=0.8), axis.title.x=element_blank(),) + scale_x_discrete(limits=c("C", "A", "B", "D"), labels=c("Columbia Current,\n CWR Current", "Columbia 2040,\n CWR Current", "Columbia Restored,\n CWR Current",  "Columbia Current,\n CWR Restored")) 
```


```{r energy lost table}
ED_used_table<-aggregate(ED_per_used~scenario, data=all_13, quantile)
ED_used_table$scenario<-as.character(ED_used_table$scenario)
ED_used_table<-format(ED_used_table, digits = 2)
ED_used_table$scenario[ED_used_table$scenario == "A"] <- "Columbia 2040, CWR Current"
ED_used_table$scenario[ED_used_table$scenario == "B"] <- "Columbia Restored, CWR Current"
ED_used_table$scenario[ED_used_table$scenario == "C"] <- "Columbia Current, CWR Current"
ED_used_table$scenario[ED_used_table$scenario == "D"] <- "Columbia Current, CWR Restored"

# create table with pretty format
kable(ED_used_table, col.names=c( "Scenario", "Minimum", "25% quantile","Median", "75% quantile", "Maximum"),row.names=FALSE, caption="Table 1. Percent energy used across different HexSim thermalscapes summarized for Snake River fall chinook salmon.", digits=1)
```


```{r import hourly}
# import in combined replicate DFs
A14<-fread("D:/Results_4Populations/snake_Columbia2040_current/combined/A5.csv", header=TRUE, sep=",")
B14<-fread("D:/Results_4Populations/snake_Columbiarestored_CWRcurrent/combined/B5.csv", header=TRUE, sep=",")
C14<-fread("D:/Results_4Populations/snake_current_current/combined/C5.csv", header=TRUE, sep=",")
D14<-fread("D:/Results_4Populations/snake_current_restoredCWR/combined/D5.csv", header=TRUE, sep=",")
# rename columns
names(A14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(B14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(C14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(D14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")

```


```{r calc DD GT 18 for each scenario}
# function to calculate cumulative degree days above a certain degree
dum_dd<-function(threshold, DF){
  DF_subset<-DF[which(DF$temp_1 >threshold),]
  dd_threshold<-aggregate(temp_1~ID, data=DF_subset, sum)
  dd_threshold$temp_1<-dd_threshold$temp_1/24
  return(dd_threshold)
}

# set threshold
thres<-18
# run for each scenario's hourly DF
A14_ddGT18<-dum_dd(thres, A14)
B14_ddGT18<-dum_dd(thres, B14)
C14_ddGT18<-dum_dd(thres, C14)
D14_ddGT18<-dum_dd(thres, D14)
# add scenario column
A14_ddGT18$scenario<-"A"
B14_ddGT18$scenario<-"B"
C14_ddGT18$scenario<-"C"
D14_ddGT18$scenario<-"D"

#combine
all_14_ddGT18<-rbind.data.frame(A14_ddGT18, B14_ddGT18, C14_ddGT18, D14_ddGT18)

```


```{r A14 hist}
a2<-ggplot(A14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,750) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia 2040, CWR Current") 
```

```{r B14 hist}
b2<-ggplot(B14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,750) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia Restored, CWR Current")
```

```{r C14 hist}
c2<-ggplot(C14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,750) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia Current, CWR Current")
```

```{r D14 hist}
d2<-ggplot(D14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,750) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia Current, CWR Restored")
```

```{r plot DD hist together, fig.cap="Fig. 3. Histograms of modeled Snake River fall chinook salmon accumulated degrees day over 18°C from Bonneville to the Snake River confluence in the Columbia River."}
plot_grid(c2, a2, b2,  d2, 
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2)
```



```{r cum DD boxplot, fig.cap="Fig. 4. Boxplots of modeled Snake River fall chinook salmon accumulated degrees day over 18°C from Bonneville to the Snake River confluence in the Columbia River."}
all_14_ddGT18$scenario<-as.factor(all_14_ddGT18$scenario)

out3<-ggplot(all_14_ddGT18, aes(x=scenario, y=temp_1, group=scenario)) +   
  geom_boxplot() + 
  labs( y="Cumulative degree days (>18°C)", title="Snake River fall chinook salmon") + 
  theme_classic() 

out3 + theme(axis.text.x=element_text(color = "black", size=11, angle=30, vjust=.8, hjust=0.8), axis.title.x=element_blank(),) + scale_x_discrete(limits=c("C", "A", "B", "D"), labels=c("Columbia Current,\n CWR Current", "Columbia 2040,\n CWR Current", "Columbia Restored,\n CWR Current",  "Columbia Current,\n CWR Restored")) 
```

```{r DD lost table}
DD_used_table<-aggregate(temp_1~scenario, data=all_14_ddGT18, quantile)
DD_used_table$scenario<-as.character(DD_used_table$scenario)
DD_used_table<-format(DD_used_table, digits = 0) # round 

DD_used_table$scenario[DD_used_table$scenario == "A"] <- "Columbia 2040, CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "B"] <- "Columbia Restored, CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "C"] <- "Columbia Current, CWR Current"
DD_used_table$scenario[DD_used_table$scenario == "D"] <- "Columbia Current, CWR Restored"

# create table with pretty format
kable(DD_used_table, col.names=c( "Scenario", "Minimum", "25% quantile","Median", "75% quantile", "Maximum"),row.names=FALSE, caption="Table 2. Cumulative degree days (>18°C) used across different HexSim thermalscapes summarized for Snake River fall chinook salmon.", digits=1)
```