---
title: '<span style=''font-size: 20px''><b>15. Energy use, CWR use, and survivorship results for Grande Ronde River summer steelhead under year 2017 temperatures for the Columbia River with simulated additional coldwater refuges</b></style>'
author: " "
date: " "
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
library(ggplot2)
library(cowplot)
library(data.table)
library(knitr)
library(chron)
```

```{r set up directories, echo=FALSE}
# to run script on different computers specify sys.info()[4] and
# specify path to model results folder and
# folder containing look up tables

# Marcia's epa computer -> NOT SET UP
if(Sys.info()[4]=="LZ2626XMSNYDE02"){
  fishdir<-path.expand("D:/Results_config_test/") # results path
  outputdir<-path.expand("D:/")
  
}

# Marcia's Lenovo -> SET UP
if(Sys.info()[4]=="DESKTOP-KMUP1V2"){
  fishdir<-path.expand("C:/Users/snyde/Dropbox/Results_config_test/")
  outputdir<-path.expand("C:/Users/snyde/Dropbox/")
  }
```

```{r plot formatting}
width1 = 4.5
height1 = 3.5
text1 = 8
```

```{r import end condition}
# import in combined replicate DFs
# GR summer steelhead
A14<-fread(paste(fishdir,"gr_Columbia2017B/combined/E13.csv", sep=""), header=TRUE, sep=",")
#B14<-fread(paste(fishdir,"gr_Columbia2017B_NoCWR/combined/E14.csv", sep=""), header=TRUE, sep=",")
C14<-fread(paste(fishdir,"gr_Columbia2017B_minus1/combined/E13.csv", sep=""), header=TRUE, sep=",")
D14<-fread(paste(fishdir,"GR_config_test/combined/E13.csv", sep=""), header=TRUE, sep=",")

# rename DF columns
names(A14)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")
# names(B13)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")
names(C14)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")
names(D14)<-c("Run", "Step", "Population", "ID", "Time_entry", "Time_exit", "Time_in_system", "Time_remaining", "Total_hours_cold_water", "Initial_weight", "Initial_energy_density", "Fitness_weight", "Fitness_energy_density", "Fitness_energy")

```


```{r created energy used for all scenarios without gamete}
# function to calculate cumulative degree days above a certain degree
avail_energy_diff<-function(DF){
  DF$gamete<-(((7598 + (0.527 * DF$Initial_weight)) * DF$Initial_weight) * 0.068) / DF$Initial_weight
DF$initial_ED_avail<-DF$Initial_energy_density-DF$gamete
# create column of energy lost
# energy_all$energy_lost<-energy_all$X11 - energy_all$X13
DF$energy_lost_gamete<-(DF$initial_ED_avail - DF$Fitness_energy) 
DF$ED_per_used<-(DF$energy_lost_gamete/DF$initial_ED_avail) * 100
return(DF)
}

A13<-avail_energy_diff(A14)
#B13<-avail_energy_diff(B13)
C13<-avail_energy_diff(C14)
D13<-avail_energy_diff(D14)

# add scenario identifying column
A13$scenario<-"A"
#B13$scenario<-"B"
C13$scenario<-"C"
D13$scenario<-"D"

# combine DFs 
all_13<-rbind.data.frame(A13,D13, C13)
```


```{r A13 hist}
a1<-ggplot(A13, aes(x=ED_per_used)) + geom_histogram(aes(x=ED_per_used, y=100 * (..count..)/sum(..count..))) + xlim(0,55) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),  title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Energy Used (%)", y="Percent", title="Columbia 2017, \nCWR Current") 
```

```{r B13 hist}
# b1<-ggplot(B13, aes(x=ED_per_used)) + geom_histogram(aes(x=ED_per_used, y=100 * (..count..)/sum(..count..))) + xlim(0,55) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
# title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Energy Used (%)", y="Percent", title="Columbia 2017, \nNo CWR")
```

```{r C13 hist}
c1<-ggplot(C13, aes(x=ED_per_used)) + geom_histogram(aes(x=ED_per_used, y=100 * (..count..)/sum(..count..))) + xlim(0,55) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Energy Used (%)", y="Percent", title="Cooler Columbia\n River (-1째C),\nCWRs Current")
```

```{r D13 hist}
d1<-ggplot(D13, aes(x=ED_per_used)) + geom_histogram(aes(x=ED_per_used, y=100 * (..count..)/sum(..count..))) + xlim(0,55) + ylim(0,25) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Energy Used (%)", y="Percent", title="Columbia 2017, \nAdded CWRs")
```

```{r plot energy hist together, fig.cap="Fig. 15.1 Histogram of percent energy lost for modeled Grande Ronde River summer steelhead migrating through four different modeled thermalscapes."}
plot_grid( a1, d1, c1,
          labels = c("A",  "B", "C"),
          ncol = 3, nrow = 1)
```


```{r energy lost boxplot, fig.cap="Fig. 15.2 Boxplot of percent energy lost for modeled Grande Ronde River summer steelhead migrating through four different modeled thermalscapes."}
all_13$scenario<-as.factor(all_13$scenario)

out2<-ggplot(all_13, aes(x=scenario, y=ED_per_used, group=scenario)) +   
  geom_boxplot() + 
  labs( y="Energy lost (%)", title="Grande Ronde River summer steelhead") + 
  theme_classic() 

out2 + theme(axis.text.x=element_text(color = "black", size=11, angle=30, vjust=.8, hjust=0.8), axis.title.x=element_blank(),) + scale_x_discrete(limits=c("A", "D", "C"), labels=c(
  "Columbia 2017,\n CWR Current",
    "Columbia 2017, \nAdded CWRs",
  "Cooler Columbia\n River (-1째C),\nCWRs Current")) 
```


```{r energy lost table}
ED_used_table<-aggregate(ED_per_used~scenario, data=all_13, quantile)
ED_used_table$scenario<-as.character(ED_used_table$scenario)
ED_used_table<-format(ED_used_table, digits = 2)
ED_used_table$scenario[ED_used_table$scenario == "A"] <- "Columbia 2017, CWR Current"
#ED_used_table$scenario[ED_used_table$scenario == "B"] <- "Columbia 2017, No CWR"
ED_used_table$scenario[ED_used_table$scenario == "C"] <- "Cooler Columbia River (-1째C), CWRs Current"
ED_used_table$scenario[ED_used_table$scenario == "D"] <- "Columbia 2017, Added CWRs"


# create table with pretty format
kable(ED_used_table, col.names=c( "Scenario", "Minimum", "25% quantile","Median", "75% quantile", "Maximum"),row.names=FALSE, caption="Table 15.1 Percent energy used across different HexSim thermalscapes summarized for Grande Ronde River summer steelhead.", digits=1)
```


```{r import refuges data, eval=TRUE, echo=FALSE}
# import refuges population census table
# only has refuge density for hours when a refuge is occupied
# import in combined replicate DFs
A9<-fread(paste(fishdir,"gr_Columbia2017B/combined/E9.csv", sep=""), header=TRUE, sep=",")
#B14<-fread(paste(fishdir,"gr_Columbia2017B_NoCWR/combined/E14.csv", sep=""), header=TRUE, sep=",")
C9<-fread(paste(fishdir,"gr_Columbia2017B_minus1/combined/E9.csv", sep=""), header=TRUE, sep=",")
D9<-fread(paste(fishdir,"GR_config_test/combined/E9.csv", sep=""), header=TRUE, sep=",")

# rename columns
colnames(A9)<-c("run","timestep","Population","ID", "refuge_id", "refuge_depth_chinook" ,"refuge_depth_steelhead", "effective_volume_chinook","effective_volume_steelhead", "current_refuge_density",
            "retain_chinook","retain_steelhead", "removed_chinook", "removed_steelhead")
# colnames(B9)<-c("run","timestep","Population","ID", "refuge_id", "refuge_depth_chinook" ,"refuge_depth_steelhead", "effective_volume_chinook","effective_volume_steelhead", "current_refuge_density",
#             "retain_chinook","retain_steelhead", "removed_chinook", "removed_steelhead")
colnames(C9)<-c("run","timestep","Population","ID", "refuge_id", "refuge_depth_chinook" ,"refuge_depth_steelhead", "effective_volume_chinook","effective_volume_steelhead", "current_refuge_density",
             "retain_chinook","retain_steelhead", "removed_chinook", "removed_steelhead")
colnames(D9)<-c("run","timestep","Population","ID", "refuge_id", "refuge_depth_chinook" ,"refuge_depth_steelhead", "effective_volume_chinook","effective_volume_steelhead", "current_refuge_density",
            "retain_chinook","retain_steelhead", "removed_chinook", "removed_steelhead")

# create dataframe to link hexsim refuge id with name of refuge
# HexSim Refuge ID in this file:
# 14 - Eagle Creek
# 15 - Rock Creek
# 16 - Herman Creek
# 17 - Wind River
# 18 - Little White Salmon River
# 19 - White Salmon River
# 20 - Klickitat River
# 21 - Deschutes River
# 22 - Umatilla River
# create sequence of refuge IDs
refuge_IDseq<-seq(14,27,1)
# create translator sequence because model adds 1 
#refuge_IDseq2<-seq(1,7,1)

# create vector of refuge names
refuge_name<-c("Eagle Creek", "Rock Creek", "Herman Creek", "Wind River", "Little White Salmon River","White Salmon River", "Klickitat River", "Deschutes River",  "experimental1", "Umatilla River", "experiment2", "experiment3", "experiment4", "experiment5")
refuge_id<-cbind.data.frame(refuge_IDseq, refuge_name) # create dataframe to link refuge ID value with refuge Name
# merge name with refuge data
A9_2<-merge(A9, refuge_id, by.x="refuge_id", by.y="refuge_IDseq")
#B9_2<-merge(B9, refuge_id, by.x="refuge_id", by.y="refuge_IDseq")
C9_2<-merge(C9, refuge_id, by.x="refuge_id", by.y="refuge_IDseq")
D9_2<-merge(D9, refuge_id, by.x="refuge_id", by.y="refuge_IDseq")

C_sum<-sum(C9_2$retain_steelhead)
A_sum<-sum(A9_2$retain_steelhead)
#B_sum<-sum(B9_2$retain_chinook)
D_sum<-sum(D9_2$retain_steelhead)
sum_v<-c(A_sum,   C_sum, D_sum)

# adjust units to h per individual
no_ind <- 20000
sum_v <- (sum_v /no_ind)

names_v<-c("Columbia 2017,CWR Current",
    "Cooler Columbia River (-1째C), CWRs Current", "Columbia 2017, Added CWRs")
refuge_use_all<-cbind.data.frame(names_v, sum_v)
kable(refuge_use_all, digits=0, col.names=c("Scenario", "CWR Residence (h/individual)"), caption="Table 15.2 Model output for hours residing in cold water refuges summarized for Grande Ronde River summer steelhead.")
```

```{r summarize dying fish}
# import in combined replicate DFs
A12<-fread(paste(fishdir,"gr_Columbia2017B/combined/E12.csv", sep=""), header=TRUE, sep=",")
#B14<-fread(paste(fishdir,"gr_Columbia2017B_NoCWR/combined/E14.csv", sep=""), header=TRUE, sep=",")
C12<-fread(paste(fishdir,"gr_Columbia2017B_minus1/combined/E12.csv", sep=""), header=TRUE, sep=",")
D12<-fread(paste(fishdir,"GR_config_test/combined/E12.csv", sep=""), header=TRUE, sep=",")


# get number of individuals died from acute temperature stress
acute_A<-((dim(A12)[1])/ 20000) * 100
#acute_B<-((dim(B12)[1])/ 6000) * 100
acute_C<-((dim(C12)[1])/ 20000) * 100
acute_D<-((dim(D12)[1])/ 20000) * 100

acute_v<-c( acute_A,  acute_C, acute_D)
acute_all<-cbind.data.frame(names_v, acute_v)
kable(acute_all,digits=2, col.names=c("Scenario", "Total mortality"), caption="Table 15.3 Model output for percent of individuals dying from acute temperature stress summarized for Grande Ronde River summer steelhead.")

```




