---
title: '<span style=''font-size: 20px''><b>16. Cumulative degree days summary results for Snake River Fall Chinook Salmon under year 2017 temperatures for the Columbia River with simulated additional coldwater refuges</b></style>'
author: " "
date: " "
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
library(ggplot2)
library(cowplot)
library(data.table)
library(knitr)
library(chron)
```

```{r set up directories, echo=FALSE}
# to run script on different computers specify sys.info()[4] and
# specify path to model results folder and
# folder containing look up tables

# Marcia's epa computer -> NOT SET UP
if(Sys.info()[4]=="LZ2626XMSNYDE02"){
  fishdir<-path.expand("D:/Results_config_test/") # results path
  outputdir<-path.expand("D:/")
  
}

# Marcia's Lenovo -> SET UP
if(Sys.info()[4]=="DESKTOP-KMUP1V2"){
  fishdir<-path.expand("C:/Users/snyde/Dropbox/Results_config_test/")
  outputdir<-path.expand("C:/Users/snyde/Dropbox/")
  }
```

```{r plot formatting}
width1 = 4.5
height1 = 3.5
text1 = 8
```

```{r import hourly}
# import in combined replicate DFs

# SR fall chinook
A14<-fread(paste(fishdir,"snake_Columbia2017B/combined/E5.csv", sep=""),header=TRUE, sep=",")
#F14<-fread(paste(fishdir,"snake_Columbia2017B_NoCWR/combined/E5.csv", sep=""),header=TRUE, sep=",")
C14<-fread(paste(fishdir,"snake_Columbia2017B_minus_1/combined/E5.csv",sep=""), header=TRUE, sep=",")
D14<-fread(paste(fishdir,"config_test_srchnk/combined/E5.csv",sep=""), header=TRUE, sep=",")


# rename columns
names(A14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
# names(B14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(C14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")
names(D14)<-c("Run", "Step", "Population", "ID", "entry_time", "exit_time", "time_in_system", "time_at_terminus", "river_km", "motivation", "temp_1", "temp_mean", "energy_density", "weight", "energy", "selector", "avoidance", "hours_cold_water_episodic", "hours_cold_water_total", "refuge_id", "hydropower")

```


```{r calc DD GT 18 for each scenario}
# function to calculate cumulative degree days above a certain degree
dum_dd<-function(threshold, DF){
  DF_subset<-DF[which(DF$temp_1 >= threshold),]
  dd_threshold<-aggregate(temp_1~ID, data=DF_subset, sum)
  dd_threshold$temp_1<-dd_threshold$temp_1/24
  return(dd_threshold)
}

# set threshold
thres<-18
# run for each scenario's hourly DF
A14_ddGT18<-dum_dd(thres, A14)
#B14_ddGT18<-dum_dd(thres, B14)
C14_ddGT18<-dum_dd(thres, C14)
D14_ddGT18<-dum_dd(thres, D14)

# add scenario column
A14_ddGT18$scenario<-"A"
#B14_ddGT18$scenario<-"B"
C14_ddGT18$scenario<-"C"
D14_ddGT18$scenario<-"D"

#combine
#all_14_ddGT18<-rbind.data.frame(A14_ddGT18, B14_ddGT18, C14_ddGT18, D14_ddGT18)
all_14_ddGT18<-rbind.data.frame(A14_ddGT18, C14_ddGT18, D14_ddGT18)

```


```{r A14 hist}
a2<-ggplot(A14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,600) + ylim(0,35) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia 2017, \nCWR Current") 
```

```{r B14 hist}
# b2<-ggplot(B14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,600) + ylim(0,35) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
#         title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia 2017, \nNo CWR")
```

```{r C14 hist}
c2<-ggplot(C14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,600) + ylim(0,35) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
         title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Cooler Columbia\n River (-1°C),\nCWRs Current")
```

```{r D14 hist}
d2<-ggplot(D14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,600) + ylim(0,35) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>18°C)", y="Percent", title="Columbia 2017, \nAdded CWRs")
```

```{r plot DD hist together, fig.cap="Fig. 16.1 Histograms of modeled Snake River Fall Chinook Salmon accumulated degrees day over 18°C from Bonneville to the Snake River confluence in the Columbia River."}
# plot_grid(a2, b2, c2, d2,
#           labels = c("A", "B", "C", "D"),
#           ncol = 2, nrow = 2)

plot_grid(a2, d2, c2,
          labels = c("A",  "B", "C"),
          ncol = 3, nrow = 1)
```

```{r cum DD boxplot, fig.cap="Fig. 16.2 Boxplots of modeled Snake River Fall Chinook Salmon accumulated degrees day over 18°C from Bonneville to the Snake River confluence in the Columbia River."}
all_14_ddGT18$scenario<-as.factor(all_14_ddGT18$scenario)

out3<-ggplot(all_14_ddGT18, aes(x=scenario, y=temp_1, group=scenario)) +   
  geom_boxplot() + 
  labs( y="Cumulative degree days (>18°C)", title="Snake River Fall Chinook Salmon") + 
  theme_classic() 

out3 + theme(axis.text.x=element_text(color = "black", size=11, angle=30, vjust=.8, hjust=0.8), axis.title.x=element_blank(),) + scale_x_discrete(limits=c( "A", "D", "C"), labels=c(
  "Columbia 2017,\n CWR Current",
    "Columbia 2017, \nAdded CWRs", 
  "Cooler Columbia\n River (-1°C),\nCWRs Current")) 
```

```{r DD lost table}
DD_used_table<-aggregate(temp_1~scenario, data=all_14_ddGT18, quantile)
DD_used_table$scenario<-as.character(DD_used_table$scenario)
DD_used_table<-format(DD_used_table, digits = 0) # round 

DD_used_table$scenario[DD_used_table$scenario == "A"] <- "Columbia 2017, CWR Current"
# DD_used_table$scenario[DD_used_table$scenario == "B"] <- "Columbia 2017, No CWR"
DD_used_table$scenario[DD_used_table$scenario == "C"] <- "Cooler Columbia River (-1°C), CWRs Current"
DD_used_table$scenario[DD_used_table$scenario == "D"] <- "Columbia 2017, Added CWRs"

# create table with pretty format
kable(DD_used_table, col.names=c( "Scenario", "Minimum", "25% quantile","Median", "75% quantile", "Maximum"),row.names=FALSE, caption="Table 16.1 Cumulative degree days (>18°C) used across different HexSim thermalscapes summarized for Snake River Fall Chinook Salmon.", digits=1)
```


```{r calc DD GT 20 for each scenario}
# function to calculate cumulative degree days above a certain degree
dum_dd<-function(threshold, DF){
  DF_subset<-DF[which(DF$temp_1 >= threshold),]
  dd_threshold<-aggregate(temp_1~ID, data=DF_subset, sum)
  dd_threshold$temp_1<-dd_threshold$temp_1/24
  return(dd_threshold)
}

# set threshold
thres<-20
# run for each scenario's hourly DF
A14_ddGT18<-dum_dd(thres, A14)
#B14_ddGT18<-dum_dd(thres, B14)
C14_ddGT18<-dum_dd(thres, C14)
D14_ddGT18<-dum_dd(thres, D14)

# add scenario column
A14_ddGT18$scenario<-"A"
#B14_ddGT18$scenario<-"B"
C14_ddGT18$scenario<-"C"
D14_ddGT18$scenario<-"D"

#combine
all_14_ddGT18<-rbind.data.frame(A14_ddGT18,  D14_ddGT18, C14_ddGT18)

```


```{r A14 GT 20 hist}
a2<-ggplot(A14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,600) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>20°C)", y="Percent", title="Columbia 2017, \nCWR Current") 
```

```{r B14 GT 20 hist}
# b2<-ggplot(B14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,600) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
#         title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>20°C)", y="Percent", title="Columbia 2017, \nNo CWR")
```

```{r C14 GT 20 hist}
c2<-ggplot(C14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,600) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
         title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>20°C)", y="Percent", title="Cooler Columbia\n River (-1°C),\nCWRs Current")
```

```{r D14 GT 20 hist}
d2<-ggplot(D14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,600) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>20°C)", y="Percent", title="Columbia 2017, \nAdded CWRs")
```

```{r plot DD hist together GT 20, fig.cap="Fig. 16.3 Histograms of modeled Snake River Fall Chinook Salmon accumulated degrees day over 18°C from Bonneville to the Snake River confluence in the Columbia River."}
plot_grid(a2, d2,c2,
          labels = c("A",  "B", "C"),
          ncol = 3, nrow = 1)
```

```{r cum DD boxplot GT 20, fig.cap="Fig. 16.4 Boxplots of modeled Snake River Fall Chinook Salmon accumulated degrees day over 18°C from Bonneville to the Snake River confluence in the Columbia River."}
all_14_ddGT18$scenario<-as.factor(all_14_ddGT18$scenario)

out3<-ggplot(all_14_ddGT18, aes(x=scenario, y=temp_1, group=scenario)) +   
  geom_boxplot() + 
  labs( y="Cumulative degree days (>20°C)", title="Snake River Fall Chinook Salmon") + 
  theme_classic() 

out3 + theme(axis.text.x=element_text(color = "black", size=11, angle=30, vjust=.8, hjust=0.8), axis.title.x=element_blank(),) + scale_x_discrete(limits=c( "A", "D", "C"), labels=c(
  "Columbia 2017,\n CWR Current",
  "Columbia 2017, \nAdded CWRs", 
  "Cooler Columbia\n River (-1°C),\nCWRs Current"
  )) 
```

```{r DD lost table GT 20}
DD_used_table<-aggregate(temp_1~scenario, data=all_14_ddGT18, quantile)
DD_used_table$scenario<-as.character(DD_used_table$scenario)
DD_used_table<-format(DD_used_table, digits = 0) # round 

DD_used_table$scenario[DD_used_table$scenario == "A"] <- "Columbia 2017, CWR Current"
# DD_used_table$scenario[DD_used_table$scenario == "B"] <- "Columbia 2017, No CWR"
DD_used_table$scenario[DD_used_table$scenario == "C"] <- "Cooler Columbia River (-1°C), CWRs Current"
DD_used_table$scenario[DD_used_table$scenario == "D"] <- "Columbia 2017, Added CWRs"

# create table with pretty format
kable(DD_used_table, col.names=c( "Scenario", "Minimum", "25% quantile","Median", "75% quantile", "Maximum"),row.names=FALSE, caption="Table 16.2 Cumulative degree days (>20°C) used across different HexSim thermalscapes summarized for Snake River Fall Chinook Salmon.", digits=1)
```


```{r calc DD GT 21 for each scenario}
# function to calculate cumulative degree days above a certain degree
dum_dd<-function(threshold, DF){
  DF_subset<-DF[which(DF$temp_1 >= threshold),]
  dd_threshold<-aggregate(temp_1~ID, data=DF_subset, sum)
  dd_threshold$temp_1<-dd_threshold$temp_1/24
  return(dd_threshold)
}

# set threshold
thres<-21
# run for each scenario's hourly DF
A14_ddGT18<-dum_dd(thres, A14)
#B14_ddGT18<-dum_dd(thres, B14)
C14_ddGT18<-dum_dd(thres, C14)
D14_ddGT18<-dum_dd(thres, D14)

# add scenario column
A14_ddGT18$scenario<-"A"
#B14_ddGT18$scenario<-"B"
C14_ddGT18$scenario<-"C"
D14_ddGT18$scenario<-"D"

#combine
all_14_ddGT18<-rbind.data.frame(A14_ddGT18,  D14_ddGT18, C14_ddGT18)

```


```{r A14 GT 21 hist}
a2<-ggplot(A14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,600) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>21°C)", y="Percent", title="Columbia 2017, \nCWR Current") 
```

```{r B14 GT 21 hist}
# b2<-ggplot(B14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,600) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
#         title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>21°C)", y="Percent", title="Columbia 2017, \nNo CWR")
```

```{r C14 GT 21 hist}
c2<-ggplot(C14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,600) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
         title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>21°C)", y="Percent", title="Cooler Columbia\n River (-1°C),\nCWRs Current")
```

```{r D14 GT 21 hist}
d2<-ggplot(D14_ddGT18, aes(x=temp_1)) + geom_histogram(aes(x=temp_1, y=100 * (..count..)/sum(..count..))) + xlim(0,600) + ylim(0,30) + theme_classic() + theme(legend.position="none", axis.text=element_text(size=text1),
        title=element_text(size=8),axis.title=element_text(size=text1)) + labs(x="Cumulative degree days (>21°C)", y="Percent", title="Columbia 2017, \nAdded CWRs")
```

```{r plot DD hist together GT 21, fig.cap="Fig. 16.5 Histograms of modeled Snake River Fall Chinook Salmon accumulated degrees day over 21°C from Bonneville to the Snake River confluence in the Columbia River."}
plot_grid(a2,  d2,c2,
          labels = c("A",  "B", "C"),
          ncol = 3, nrow = 1)
```

```{r cum DD boxplot GT 21, fig.cap="Fig. 16.6 Boxplots of modeled Snake River Fall Chinook Salmon accumulated degrees day over 21°C from Bonneville to the Snake River confluence in the Columbia River."}
all_14_ddGT18$scenario<-as.factor(all_14_ddGT18$scenario)

out3<-ggplot(all_14_ddGT18, aes(x=scenario, y=temp_1, group=scenario)) +   
  geom_boxplot() + 
  labs( y="Cumulative degree days (>21°C)", title="Snake River Fall Chinook Salmon") + 
  theme_classic() 

out3 + theme(axis.text.x=element_text(color = "black", size=11, angle=30, vjust=.8, hjust=0.8), axis.title.x=element_blank(),) + scale_x_discrete(limits=c( "A", "D", "C"), labels=c(
  "Columbia 2017,\n CWR Current",
  "Columbia 2017, \nAdded CWRs", "Cooler Columbia\n River (-1°C),\nCWRs Current")) 
```

```{r DD lost table GT 21}
DD_used_table<-aggregate(temp_1~scenario, data=all_14_ddGT18, quantile)
DD_used_table$scenario<-as.character(DD_used_table$scenario)
DD_used_table<-format(DD_used_table, digits = 0) # round 

DD_used_table$scenario[DD_used_table$scenario == "A"] <- "Columbia 2017, CWR Current"
#DD_used_table$scenario[DD_used_table$scenario == "B"] <- "Columbia 2017, No CWR"
DD_used_table$scenario[DD_used_table$scenario == "C"] <- "Cooler Columbia River (-1°C),CWRs Current"
DD_used_table$scenario[DD_used_table$scenario == "D"] <- "Columbia 2017, Added CWRs"

# create table with pretty format
kable(DD_used_table, col.names=c( "Scenario", "Minimum", "25% quantile","Median", "75% quantile", "Maximum"),row.names=FALSE, caption="Table 16.3 Cumulative degree days (>21°C) used across different HexSim thermalscapes summarized for Snake River Fall Chinook Salmon.", digits=1)
```

